### ISSUE TITLE
Gradle 4.0: Project evaluating: ClassNotFoundException: org.gradle.internal.operations.BuildOperationProcessor

### ISSUE THREAD

**Issue by remal** [gogradle/gogradle#106]
I get ClassNotFoundException on project evaluating:
```
org.gradle.api.GradleScriptException: A problem occurred evaluating project ':starter'.
.......................
Caused by: java.lang.NoClassDefFoundError: org/gradle/internal/operations/BuildOperationProcessor
	at com.github.blindpirate.gogradle.GogradleModule.configure(GogradleModule.java:123)
	at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
	at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
	at com.google.inject.spi.Elements.getElements(Elements.java:110)
	at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
	at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
	at com.google.inject.Guice.createInjector(Guice.java:99)
	at com.google.inject.Guice.createInjector(Guice.java:73)
	at com.google.inject.Guice.createInjector(Guice.java:62)
	at com.github.blindpirate.gogradle.GolangPlugin.initGuice(GolangPlugin.java:60)
	at com.github.blindpirate.gogradle.GolangPlugin.init(GolangPlugin.java:80)
	at com.github.blindpirate.gogradle.GolangPlugin.apply(GolangPlugin.java:65)
	at com.github.blindpirate.gogradle.GolangPlugin.apply(GolangPlugin.java:46)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:41)
	at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:49)
	at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:165)
	at org.gradle.api.internal.plugins.DefaultPluginManager.access$200(DefaultPluginManager.java:47)
	at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:252)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
	at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:125)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.applyType(DefaultObjectConfigurationAction.java:113)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.access$200(DefaultObjectConfigurationAction.java:36)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction$3.run(DefaultObjectConfigurationAction.java:80)
	at org.gradle.api.internal.plugins.DefaultObjectConfigurationAction.execute(DefaultObjectConfigurationAction.java:136)
	at org.gradle.api.internal.project.AbstractPluginAware.apply(AbstractPluginAware.java:46)
	at org.gradle.api.internal.project.ProjectScript.apply(ProjectScript.java:34)
	at org.gradle.api.Script$apply$0.callCurrent(Unknown Source)
	at build_3en383r0hdpuaimo5k56dsfag.run(Unknown Source)
	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
	... 89 more
Caused by: java.lang.ClassNotFoundException: org.gradle.internal.operations.BuildOperationProcessor
	... 122 more
```

This exception occures on 4.0 Gradle version.

**Comment by blindpirate** [comment]
Thanks @remal , I just confirmed this will occur in `4.0`, but I think it shouldn't happen in `3.5` because I have been using `3.5` for a long time and don't encounter this problem. Could you please tell me what environment you are in? I mean OS, JDK, etc.

**Comment by blindpirate** [comment]
And I confirmed the reason is that `BuildOperationProcessor` is removed in `4.0`, but it does exist in Gradle 3.5
 [https://github.com/gradle/gradle/blob/v3.5.0/subprojects/base-services/src/main/java/org/gradle/internal/operations/BuildOperationProcessor.java](https://github.com/gradle/gradle/blob/v3.5.0/subprojects/base-services/src/main/java/org/gradle/internal/operations/BuildOperationProcessor.java). Sorry for the inconvenience, I believe Gogradle will release a new version to be compatible with `4.0` this week.

**Comment by remal** [comment]
@blindpirate, you are right. I don't see this error for Gradle 3.5.

**Comment by blindpirate** [comment]
OK, please use Gradle 3.5 as a workaround, I used an internal API to render test report HTML because I have no choice.

**Comment by blindpirate** [comment]
The latest version of Gogradle has supported both 3.5 and 4.0, please let me know if there's any issue.
