### ISSUE TITLE
版本冲突问题

### ISSUE THREAD

**Issue by JackTiger** [gogradle/gogradle#110]
我本地构建时，遇到这样的问题，我依赖库A里有vendor(依赖github.com/gogo/protobuf)
我有另外一个依赖库B(ETCD)，解析时使用了protobuf的版本比较高(依赖github.com/gogo/protobuf)
我在打印依赖树时看到

`|-- github.com/gogo/protobuf:100ba4e [., proto] (*)`

**中括号里是指什么？是指只拷贝这一部分的代码吗？** 

这样A版本里依赖于github.com/gogo/protobuf/gogoproto 被B中的较高版本冲掉了，导致我在构建时找不到github.com/gogo/protobuf/gogoproto这个包，解决冲突时只保留了github.com/gogo/protobuf/proto 这个包，这个很奇怪，我看了下github上，新版本是有github.com/gogo/protobuf/gogoproto这个包的，为啥被干掉了？

**Comment by blindpirate** [comment]
括号里面是subpackage。[etcd的glide.lock](https://github.com/coreos/etcd/blob/master/glide.lock#L39)指定了subpackage，所以没有`github.com/gogo/protobuf/gogoproto`。

**Comment by JackTiger** [comment]
我在构建case，提示：

```
buildscript {
    dependencies {
        classpath files('D:/progma/gogradle-0.5.4-all.jar')
    }
}

apply plugin: 'com.github.blindpirate.gogradle'

golang {
    packagePath = 'github.com/JackTiger/demoB' // 欲构建项目的path，不是项目的磁盘路径！
}

dependencies {
    golang {
        build name:"github.com/JackTiger/demoC"
    }
}
```

我在构建时，提示：
```
D:\progma\src\github.com\JackTiger\demoB>gradle build

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\progma\src\github.com\JackTiger\demoB\build.gradle' line: 15

* What went wrong:
A problem occurred evaluating root project 'demoB'.
> org.gradle.internal.metaobject.DynamicObject.setProperty(Ljava/lang/String;Lja
va/lang/Object;Lorg/gradle/internal/metaobject/SetPropertyResult;)V

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug
option to get more log output.

BUILD FAILED in 2s
```


我使用的gradle版本
```
D:\progma\src\github.com\JackTiger\demoB>gradle -version

------------------------------------------------------------
Gradle 4.0
------------------------------------------------------------

Build time:   2017-06-14 15:11:08 UTC
Revision:     316546a5fcb4e2dfe1d6aa0b73a4e09e8cecb5a5

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_111 (Oracle Corporation 25.111-b14)
OS:           Windows 7 6.1 x86
```

**Comment by blindpirate** [comment]
Gogradle使用了一些Gradle的内部API，所以4.0和0.5.4不兼容。Gogradle 0.6.0+ 才支持Gradle 4.0.

**Comment by JackTiger** [comment]
```
Execution failed for task ':resolveBuildDependencies'.
> Exception in resolution, message is:
vendor dependency code.xxxx.com/do-libraries:GitNotationDependency{name='code.xxxx.com/prp/basicfunction', commit='3a91a241c94eb69645acb6dfefd2c812444475fc', urls='[git@code.xxxx.com:prp/basicfunction.git]'}/vendor/code.xxxx.com/do-libraries/Oscar-Go does not exist in transitive dependencies of code.xxxx.com/prp/basicfunction#3a91a241c94eb69645acb6dfefd2c812444475fc
Resolution stack is:
|-code.xxxx.com/ps_5g_cp/proc_demo
 |-code.xxxx.com/ps_5g_cp/platypus#c05aa42c98542b6f3f4879523db9a02369e6226e

```

**Comment by JackTiger** [comment]
gogradle.lock中的定义

```

- name: "code.xxxx.com/do-libraries/Oscar-Go"
--
  | host:
  | name: "code.xxxx.com/prp/basicfunction"
  | commit: "3a91a241c94eb69645acb6dfefd2c812444475fc"
  | url: "git@code.xxxx.com:prp/basicfunction.git"
  | vcs: "git"
  | vendorPath: "vendor/code.xxxx.com/do-libraries/Oscar-Go"
  | transitive: false


```

**Comment by JackTiger** [comment]
有个问题，想咨询下你，我用gogradle生成了vendor（没有生成gogradle.lock），然后提交入库，作为别人的依赖时，构建时会报如下的问题;(有时不影响构建，正常吗)

```
Exception in accessing https://code.xxxxx.com/do-libraries
java.net.SocketTimeoutException: connect timed out
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
        at com.github.blindpirate.gogradle.util.HttpUtils.fetchAsInputStream(HttpUtils.java:138)
        at com.github.blindpirate.gogradle.util.HttpUtils.fetch(HttpUtils.java:100)
        at com.github.blindpirate.gogradle.util.HttpUtils.get(HttpUtils.java:54)

```

**Comment by JackTiger** [comment]
```
13:33:44.847 [DEBUG] [com.github.blindpirate.gogradle.util.logging.DebugLogMethodInterceptor] Entering method produce of class DefaultPackagePathResolver$$EnhancerByGuice$$49e0383b, the arguments is [code.xxx.com/do-libraries]
13:33:44.848 [DEBUG] [com.github.blindpirate.gogradle.util.logging.DebugLogMethodInterceptor] Exiting method produce of class DefaultPackagePathResolver$$EnhancerByGuice$$49e0383b, total time is 0.025 ms, return Optional[VcsGolangPackage{path='code.huawei.com/do-libraries', rootPath='code.xxx.com/do-libraries', vcsType=GIT, urls='[http://code.xxxx.com/do-libraries.git]'}]
13:33:44.848 [DEBUG] [com.github.blindpirate.gogradle.core.dependency.produce.SecondPassVendorDirectoryVisitor] Produce recognized package code.xxx.com/do-libraries.
13:33:44.848 [DEBUG] [com.github.blindpirate.gogradle.util.ProcessUtils] Forking process: args [git, log, -1, --pretty=format:%ct, vendor/code.xxxx.com/do-libraries], envs {}, workingDir C:\Users\l00377907\.gradle\go\gopath\code.xxxx.com\prp\basicfunction

```

**Comment by JackTiger** [comment]
另外，为何这边解析的只有两级目录：

`13:33:00.812 [DEBUG] [com.github.blindpirate.gogradle.util.logging.DebugLogMethodInterceptor] Entering method produce of class DefaultPackagePathResolver$$EnhancerByGuice$$49e0383b, the arguments is [code.xxxx.com/do-libraries]`

**Comment by JackTiger** [comment]
```
root@k8s-master:/tmp/.ansible/files# curl -X GET http://code.XXXX.com/do-libraries?go-get=1
<!DOCTYPE html><html><head><meta content='code.XXXX.com/do-libraries git http://code.XXXX.com/do-libraries.git' name='go-import'></head></html>

```

**Comment by JackTiger** [comment]
```
https://gitlab.com/JackTiger?go-get=1

<meta content="gitlab.com/JackTiger git https://gitlab.com/JackTiger.git" name="go-import">
```

```
https://gitlab.com/JackTiger/TestLargeFile?go-get=1
<meta content="gitlab.com/JackTiger/TestLargeFile git https://gitlab.com/JackTiger/TestLargeFile.git" name="go-import">
```

**Comment by JackTiger** [comment]
你的意思是：比如我需要添加code.XXXX.com/do-libraries/Oscar-Go

我需要添加

```
dependencies {
      golang {
             build 'code.xxx.com/do-libraries/unused'
             build 'code.XXXX.com/do-libraries/Oscar-Go'
      }
}
```

**Comment by JackTiger** [comment]
按照上周五你的建议：
我本地两次的构建依赖以及构建树如下：

第一次
```
    [name: 'code.xxxx.com/prp/basicfunction', commit: '3a91a241c94eb69645acb6dfefd2c812444475fc']
```
生成的构建树：
```
code.xxxx.com/xxxx/proc_demo
\-- code.xxxx.com/prp/basicfunction:3a91a24
    |-- code.xxxx.com/CSP-GSF:code.xxxx.com/prp/basicfunction#3a91a241c94eb69645acb6dfefd2c812444475fc/vendor/code.xxxx.com/CSP-GSF
    |-- code.xxxx.com/cse:code.xxxx.com/prp/basicfunction#3a91a241c94eb69645acb6dfefd2c812444475fc/vendor/code.xxxx.com/cse
    |-- code.xxxx.com/do-libraries:code.xxxx.com/prp/basicfunction#3a91a241c94eb69645acb6dfefd2c812444475fc/vendor/code.xxxx.com/do-libraries
```


第二次
```
    [name: 'code.xxxx.com/do-libraries/Oscar-Go'],
    [name: 'code.xxxx.com/prp/basicfunction', commit: '3a91a241c94eb69645acb6dfefd2c812444475fc']
```
生成的构建树：
```
code.xxxx.com/ps_5g_cp/proc_demo
|-- code.xxxx.com/do-libraries/Oscar-Go:034a4b4
-- code.xxxx.com/prp/basicfunction:3a91a24
    |-- code.xxxx.com/CSP-GSF:code.xxxx.com/prp/basicfunction#3a91a241c94eb69645acb6dfefd2c812444475fc/vendor/code.xxxx.com/CSP-GSF
    |-- code.xxxx.com/cse:code.xxxx.com/prp/basicfunction#3a91a241c94eb69645acb6dfefd2c812444475fc/vendor/code.xxxx.com/cse
    |-- code.xxxx.com/do-libraries/Oscar-Go:code.xxxx.com/prp/basicfunction#3a91a241c94eb69645acb6dfefd2c812444475fc/vendor/code.xxxx.com/do-libraries/Oscar-Go -> 034a4b4 (*)
```

从两次的依赖树来看，的确加了code.xxxx.com/do-libraries/Oscar-Go之后，第二次的构建数，解析式按照code.xxxx.com/do-libraries/Oscar-Go这个来解析了，但是对于其他vendor里的依赖还跟原来一样，即我需要将我用到的所有的vendor中的依赖都加到我欲构建的项目的dependencies中，这有些麻烦，这也是我上周困惑的地方。

我们一起想想能否有更优的方案解决这个问题。
我的理解：
1.对于vendor从三级目录往前解析
2.或者针对gitlab这类的特殊处理下(在gitlab bug修复前)

**Comment by blindpirate** [comment]
目前只有这个workaround，对于每个二级目录，都额外声明一下以保证正确地扫描vendor。解决方案我已经有了，不过要到周三才能开始着手去做。

1.vendor从三级目录往前解析不可行。
2.无法区分什么样的包是gitlab提供的，什么样的不是。

**Comment by JackTiger** [comment]
好的，那就等你的下个版本再升级。谢谢!
