### ISSUE TITLE
java.lang.NoClassDefFoundError: org/gradle/internal/operations/BuildOperationProcessor

### ISSUE THREAD

**Issue by Jamie-sas** [gogradle/gogradle#142]
build.gradle, using a couple of internal plugins, and project name changed from actual:
`buildscript {
    repositories {
        mavenCentral()
        maven {
            url "${repository_contextUrl}/plugins-release"
        }
    }
    dependencies {
        classpath "com.sas.gradle.plugins:satisfactory:1.+"
        classpath "com.sas.gradle.plugins:onepm:4.+"
    }
}

plugins {
    id 'com.github.blindpirate.gogradle' version '0.4.5'
}

apply plugin: 'satisfactory'
apply plugin: 'onepm'
apply plugin: 'eclipse'
apply plugin: 'idea'

golang {
    packagePath = 'myProj/src/myProj'
}

goBuild {
    targetPlatform = ['linux-amd64', 'linux-386', 'freebsd-amd64', 'freebsd-386', 'darwin-amd64', 'darwin-386', 'windows-amd64', 'windows-386']
    go 'goBuild -o .gogradle/${GOOS}_${GOARCH}_${PROJECT_NAME}${GOEXE} myProj'
}

task wrapper(type: Wrapper) {
    gradleVersion = project.getProperty('gradle.version')
    distributionUrl = "${project.getProperty('gradle.distribution.url.prefix')}/${gradleVersion}/gradle-${gradleVersion}-bin.zip"
}

dependencies {
    golang {
        build name:'github.com/hashicorp/consul', version:'a9afa0c27f484dd19fe59a80444e64e5352c4408', subpackages:[".","api"]
        build name:'github.com/hashicorp/go-cleanhttp', version:'ad28ea4487f05916463e2423a55166280e8254b5'
        build name:'github.com/hashicorp/serf', version:'44157f9dfdbcf6d9e20fcfd52cfee348dbc467ee', subpackages:[".","coordinate"]
        build name:'github.com/stretchr/testify', version:'69483b4bd14f5845b5a1e55bca19e954e827f1d0', subpackages:[".","assert"]
        build name:'gopkg.in/yaml.v2', version:'cd8b52f8269e0feb286dfeef29f8fe4d5b397e0b'
        test name:'github.com/davecgh/go-spew', version:'6d212800a42e8ab5c146b8ace3490ee17e5225f9', subpackages:[".","spew"]
        test name:'github.com/pmezard/go-difflib', version:'d8ed2627bdf02c080bf22230dbb337003b7aba2d', subpackages:["difflib","."]
    }
}
`

Using Gradle 4.0.2, fails miserably unless I turn on gogradle task aliases and use them, due to conflict with internal 'build'.

Start the build instead with

`gradle goBuild`

During "Resolve files for classpath", exception is thrown:

`FAILURE: Build failed with an exception.

* What went wrong:
org/gradle/internal/operations/BuildOperationProcessor

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
java.lang.NoClassDefFoundError: org/gradle/internal/operations/BuildOperationProcessor
        at com.github.blindpirate.gogradle.GogradleModule.configure(GogradleModule.java:105)
        at com.google.inject.AbstractModule.configure(AbstractModule.java:62)
        at com.google.inject.spi.Elements$RecordingBinder.install(Elements.java:340)
        at com.google.inject.spi.Elements.getElements(Elements.java:110)
        at com.google.inject.internal.InjectorShell$Builder.build(InjectorShell.java:138)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:104)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at com.github.blindpirate.gogradle.GolangPlugin.initGuice(GolangPlugin.java:43)
        at com.github.blindpirate.gogradle.GolangPlugin.init(GolangPlugin.java:65)
        at com.github.blindpirate.gogradle.GolangPlugin.apply(GolangPlugin.java:48)
        at com.github.blindpirate.gogradle.GolangPlugin.apply(GolangPlugin.java:28)
        at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:41)
        at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:49)
        at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:165)
        at org.gradle.api.internal.plugins.DefaultPluginManager.access$200(DefaultPluginManager.java:47)
        at org.gradle.api.internal.plugins.DefaultPluginManager$AddPluginBuildOperation.run(DefaultPluginManager.java:252)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
        at org.gradle.api.internal.plugins.DefaultPluginManager.apply(DefaultPluginManager.java:125)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator$5.run(DefaultPluginRequestApplicator.java:172)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:210)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:169)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:167)
        at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:61)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:58)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:39)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.doConfigure(LifecycleProjectEvaluator.java:63)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.access$100(LifecycleProjectEvaluator.java:33)
        at org.gradle.configuration.project.LifecycleProjectEvaluator$ConfigureProject.run(LifecycleProjectEvaluator.java:103)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:49)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:654)
        at org.gradle.api.internal.project.DefaultProject.evaluate(DefaultProject.java:132)
        at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
        at org.gradle.execution.TaskPathProjectEvaluator.configureHierarchy(TaskPathProjectEvaluator.java:60)
        at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:38)
        at org.gradle.initialization.DefaultGradleLauncher$ConfigureBuild.run(DefaultGradleLauncher.java:195)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:157)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:44)
        at org.gradle.initialization.DefaultGradleLauncher$1.run(DefaultGradleLauncher.java:122)
        at org.gradle.internal.work.DefaultWorkerLeaseService$2.execute(DefaultWorkerLeaseService.java:124)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:116)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:99)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:66)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$1.run(RunAsBuildOperationBuildActionRunner.java:43)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:95)
        at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
        at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:44)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:75)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:49)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:51)
        at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:32)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
        at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:64)
        at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:29)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
        at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:42)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:50)
        at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:30)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)

BUILD FAILED in 2s
`

This is an _old_ project, but I tried with gradlew anyway... it is set up to use gradle 2.14.1, and the failure is:

`> Illegal target platform:[linux-amd64, linux-386, freebsd-amd64, freebsd-386, darwin-amd64, darwin-386, windows-amd64, windows-386]
`

Is there a particular version of gradle that must be used with gogradle?  If so, could the plugin just abort and tell me that if I'm not using what it expects?  :-\

**Comment by blindpirate** [comment]
You're using the old version of Gogradle, try latest (`0.7.0`).

PS. There's a tiny error in your `build.gradle`:

```
goBuild {
    targetPlatform = ['linux-amd64', 'linux-386', 'freebsd-amd64', 'freebsd-386', 'darwin-amd64', 'darwin-386', 'windows-amd64', 'windows-386']
    go 'goBuild -o .gogradle/${GOOS}${GOARCH}${PROJECT_NAME}${GOEXE} myProj'
}
```
should be 

```
goBuild {
    targetPlatform = ['linux-amd64', 'linux-386', 'freebsd-amd64', 'freebsd-386', 'darwin-amd64', 'darwin-386', 'windows-amd64', 'windows-386']
    go 'build -o .gogradle/${GOOS}${GOARCH}${PROJECT_NAME}${GOEXE} myProj'
}
```

Because `go build` is actually a command.

**Comment by Jamie-sas** [comment]
Bleh.  gogradle version was a direct paste from the online doc.  I should've caught that and updated it.

go goBuild was a "replace all" problem, from replacing the name of the config.

At any rate, I don't know if this will work or not because no I'm being prompted for a password when I run 'gradle goVendor'.  GitHub suddenly wants to know who I am during dependency resolution.

**Comment by Jamie-sas** [comment]
No idea what was going on with github, but after deleting EVERYTHING that wasn't part of the original project (vendor subdir, build subdir, .gogradle, etc., etc.) and trying again, it finally got past the dependencies.

Now, however, I'm running into a problem similar to another I posted recently - gogradle doesn't work with the recommended layout from golang.  This project was laid out with 'src' and 'pkg' subdirs per those recommendations, and gogradle is failing to build the project because it can't find the things in the pkg subdir.

For example, given this path under the root of the project:

    pkg/config  (contains 2 files - config.go and config_test.go)

 it is looking for

    .gogradle/project_gopath/src/myproj/vendor/<server>/golang/myproj/pkg/config

but the location under .gogradle is actually

    .gogradle/project_gopath/src/myproj/pkg/config

Which is still not correct, but is where gogradle copied the files.

**Comment by blindpirate** [comment]
It seems that the password thing during dependency resolution is due to inappropriate configuration of your git. Gogradle will try to invoke something like `git pull` to fetch code from github, and when git encounters a repository which needs authorization, the password prompt emerges.

I'm not sure I fully understand your second question. However, you mentioned `recommended layout of golang`, it seems that you have some tiny misunderstandings. If you're using "recommended layout", the structure should be (see [here](https://golang.org/cmd/go/#hdr-GOPATH_environment_variable)):

```
<global GOPATH environment variable>
|- src
|   |- github.com
|     |- golang
|        |- myproj
|           |- build.gradle
|           |- config
|              |- config.go
|- pkg
    |- <some files generated by golang, go source files shouldn't be here>
```

And your structure totally confused me... what's the `import path` of your project root? What're the `import`s in your `pkg/config/config.go` file?

**Comment by Jamie-sas** [comment]
My apologies... I misread the section on golang.org.  You are completely correct that 'pkg' shouldn't contain go src.  It appears this project I've been trying to make work is simply... wrong.

The build.gradle file being used in the past was extremely complex, creating multiple tasks at runtime and then running them.

Looks like I need to go back to that original build.gradle to try to find out what is going on with their version of the pkg subdir.

Thank you for the earlier help, pointing out the version and goBuild vs build problems.

**Comment by blindpirate** [comment]
Glad to help, please feel free to ask questions.

**Comment by Jamie-sas** [comment]
I have found the source of confusion in this project.

Although the standard layout in the docs say that there should only be linkable packages in the pkg subdir, the documentation on creating packages tells you to put the source in there to compile it into the .a files.  See this page:

(https://www.golang-book.com/books/intro/11)

Since this project was created a while ago, the official docs were the only real place to look for information on such things, so that is why the source is where it is.

However, this presents a problem - how do I convince gogradle to build these pkg files first?

**Comment by blindpirate** [comment]
The answer is Gogradle don't guarantee that. Actually, what Gogradle does is just forking a process to run `go build`, so it's totally handled by go itself. 

As for `package`, I guess you confuse "language package" and "object package". The link you mentioned is totally "language package" and it has noting to do with `pkg` directory and `.a` files. Here's my advice: forget `pkg` directory, don't care what's inside, just need write source code in `src` and that's all.

**Comment by Jamie-sas** [comment]
The problem is in my attempting to unravel what has already been done in a commercial environment.  I don't necessarily have the freedom to rearrange the code of an already shipping object.  However, I can at least try, since, as you say, this particular part is NOT to the standard.
