### ISSUE TITLE
BuildDarwinAmd64 task fails with exception but no detailed error 

### ISSUE THREAD

**Issue by timleung22** [gogradle/gogradle#157]
My build fails on the taask :buildDarwinAmd64.  Turned on debug log and stack trace and this is what I got
09:01:44.122 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':buildDarwinAmd64'.
09:01:44.122 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Execute doFirst {} action for :buildDarwinAmd64' started
09:01:44.122 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Execute doFirst {} action for :buildDarwinAmd64'
09:01:44.123 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Build operation 'Execute executeTask for :buildDarwinAmd64' started
09:01:44.161 [DEBUG] [com.github.blindpirate.gogradle.util.ProcessUtils] Forking process: args [/usr/local/go/bin/go, build, ./cmd/...], envs {GOEXE=, GOPATH=/Users/trpfe96/Projects/Fusion/protoc-gen-doc/.gogradle/project_gopath, GOROOT=/usr/local/go, GOOS=darwin, GOARCH=amd64}, workingDir /Users/trpfe96/Projects/Fusion/protoc-gen-doc
09:01:44.284 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Execute executeTask for :buildDarwinAmd64'
09:01:44.285 [DEBUG] [org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter] Removed task artifact state for {} from context.
09:01:44.285 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':buildDarwinAmd64'
...
09:01:44.286 [DEBUG] [org.gradle.internal.progress.DefaultBuildOperationExecutor] Completing Build operation 'Run tasks'
09:01:44.287 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
09:01:44.287 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
09:01:44.287 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
09:01:44.287 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
09:01:44.287 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':buildDarwinAmd64'.
09:01:44.287 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > Build failed due to return code 1 of: 
09:01:44.287 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Command:
09:01:44.287 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    /usr/local/go/bin/go build ./cmd/...
09:01:44.287 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   Env:
09:01:44.287 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    GOEXE=
09:01:44.287 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    GOPATH=/Users/trpfe96/Projects/Fusion/protoc-gen-doc/.gogradle/project_gopath
09:01:44.287 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    GOROOT=/usr/local/go
09:01:44.287 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    GOOS=darwin
09:01:44.287 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]    GOARCH=amd64
09:01:44.288 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 
09:01:44.288 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
09:01:44.288 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':buildDarwinAmd64'.
09:01:44.288 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
09:01:44.288 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)

But the same command,  /usr/local/go/bin/go build ./cmd/..., runs successfully at the project's directory.

**Comment by timleung22** [comment]
resolved, see issue #158
