### ISSUE TITLE
Build should run in offline mode if there is no changes in dependencies

### ISSUE THREAD

**Issue by amimas** [gogradle/gogradle#199]
I noticed today that I couldn't build my project in offline mode. To run in offline mode, I run `gradlew clean build --offline`. This produced following error message:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':custom-docker-log-driver:resolveBuildDependencies'.
> Exception in resolution, message is:
  vendor dependency cloud.google.com/go:github.com/docker/docker: commit='90d35abf7b3535c1c319c872900fbd76374e521c', urls=[https://github.com/docker/docker.git, git@github.com:docker/docker.git]/vendor/cloud.google.com/go does not exist in transitive dependencies of github.com/docker/docker#90d35abf7b3535c1c319c872900fbd76374e521c
```

The stacktrace of the error contains this:

```
Caused by: com.github.blindpirate.gogradle.core.exceptions.DependencyResolutionException: vendor dependency cloud.google.com/go:github.com/docker/docker: commit='90d35abf7b3535c1c319c872900fbd76374e521c', urls=[https://github.com/docker/docker.git, git@github.com:docker/docker.git]/vendor/cloud.google.com/go does not exist in transitive dependencies of github.com/docker/docker#90d35abf7b3535c1c319c872900fbd76374e521c
        at com.github.blindpirate.gogradle.core.exceptions.DependencyResolutionException.vendorNotExist(DependencyResolutionException.java:66)
        at com.github.blindpirate.gogradle.core.dependency.VendorNotationDependency.doResolve(VendorNotationDependency.java:65)
        at com.github.blindpirate.gogradle.core.dependency.AbstractNotationDependency.resolve(AbstractNotationDependency.java:55)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.createSubContextAndResolve(DependencyTreeFactory.java:92)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.lambda$resolve$0(DependencyTreeFactory.java:77)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.resolve(DependencyTreeFactory.java:78)
        ... 45 more
```

I did not have any changes in my golang dependencies. If I run `gradlew clean build`, the project completes successfully.

**Comment by blindpirate** [comment]
Thanks for reporting, I'll investigate it.
