### ISSUE TITLE
java.net.SocketTimeoutException: connect timed out?

### ISSUE THREAD

**Issue by JackTiger** [gogradle/gogradle#220]
咨询下，执行gogradle时报如下错误，可能的原因是什么？

```
Caused by: java.net.SocketTimeoutException: connect timed out
        at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at com.github.blindpirate.gogradle.util.HttpUtils.fetchAsInputStream(HttpUtils.java:138)
        at com.github.blindpirate.gogradle.util.HttpUtils.fetch(HttpUtils.java:100)
        at com.github.blindpirate.gogradle.util.HttpUtils.get(HttpUtils.java:54)
        at com.github.blindpirate.gogradle.util.HttpUtils.get(HttpUtils.java:49)
        at com.github.blindpirate.gogradle.crossplatform.DefaultGoBinaryManager.fetchNewestStableVersion(DefaultGoBinaryManager.java:164)
```

**Comment by blindpirate** [comment]
如果没指定go版本，机器上也没安装，会访问http://gogradle.oss-cn-hongkong.aliyuncs.com/newest-stable-go-version.txt 以获取最新的go版本号，我想你们的生产环境可能关闭了外网访问。

**Comment by JackTiger** [comment]
恩，好的，谢谢，就是这个问题导致的。

我咨询下，现在我们应用gogradle时，由于依赖比较多，导致解析依赖这块速度比较慢，所以我想咨询下gogradle这块是否还能提高解析依赖的速度，想咨询下你的建议，谢谢！
