### ISSUE TITLE
Gradle build daemon disappeared unexpectedly 

### ISSUE THREAD

**Issue by JackTiger** [gogradle/gogradle#233]
咨询下执行GoGradle构建时，经常出现下面的问题
```
FAILURE: Build failed with an exception.
09:34:10 
09:34:10 * What went wrong:
09:34:10 Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
09:34:10 
09:34:10 * Try:
09:34:10 Run with --debug option to get more log output. Run with --scan to get full insights.
09:34:10 
09:34:10 * Exception is:
09:34:10 org.gradle.launcher.daemon.client.DaemonDisappearedException: Gradle build daemon disappeared unexpectedly (it may have been killed or may have crashed)
09:34:10 	at org.gradle.launcher.daemon.client.DaemonClient.handleDaemonDisappearance(DaemonClient.java:238)
09:34:10 	at org.gradle.launcher.daemon.client.DaemonClient.monitorBuild(DaemonClient.java:214)
09:34:10 	at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:178)
09:34:10 	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:141)
09:34:10 	at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:92)
09:34:10 	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
09:34:10 	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
09:34:10 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:291)
09:34:10 	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:264)
09:34:10 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:33)
09:34:10 	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
09:34:10 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
09:34:10 	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
09:34:10 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:257)
09:34:10 	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:191)
09:34:10 	at org.gradle.launcher.Main.doAction(Main.java:33)
09:34:10 	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
09:34:10 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:34:10 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09:34:10 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:34:10 	at java.lang.reflect.Method.invoke(Method.java:498)
09:34:10 	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
09:34:10 	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
09:34:10 	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
09:34:10 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
09:34:10 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
09:34:10 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
09:34:10 	at java.lang.reflect.Method.invoke(Method.java:498)
09:34:10 	at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:31)
09:34:10 	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
09:34:10 	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
09:34:10 
```

Gradle Version

```
$ ./gradlew --version

------------------------------------------------------------
Gradle 4.4
------------------------------------------------------------

Build time:   2017-12-06 09:05:06 UTC
Revision:     cf7821a6f79f8e2a598df21780e3ff7ce8db2b82

Groovy:       2.4.12
Ant:          Apache Ant(TM) version 1.9.9 compiled on February 2 2017
JVM:          1.8.0_144 (Oracle Corporation 25.144-b01)
OS:           Windows 7 6.1 amd64

Picked up JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF8


```

**Comment by blindpirate** [comment]
两种情况，一种是内存不够被系统杀掉了，这种情况调大xmx。另外一种是JVM本身crash掉了，在工作目录下一般会有crash的日志，其中会有线索。

**Comment by JackTiger** [comment]
好的，谢谢，可能与我本地的配置有关系

`org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8`

最大非堆内存分配小了

**Comment by JackTiger** [comment]
@blindpirate 咨询个问题，gradle里能否获取exec执行的返回值，比如：

```
task execDemo(){
    doLast {
        exec {
            commandLine "bash", "./build.sh"
        }
    }
}
```

这个任务中，我如何能够获取到exec执行的结果？

**Comment by blindpirate** [comment]
https://github.com/gradle/gradle/blob/587e778d768f488f7acf77673f9c72c65517bf8a/subprojects/process-services/src/main/java/org/gradle/process/ExecResult.java#L28 <https://github.com/gradle/gradle/blob/587e778d768f488f7acf77673f9c72c65517bf8a/subprojects/process-services/src/main/java/org/gradle/process/ExecResult.java#L28>

**Comment by JackTiger** [comment]
好的，谢谢！

另外咨询下我们在resolveBuildDependencies任务中，下面的操作主要是用来做什么的？

`[git, submodule, update, --init, --recursive]`

**Comment by blindpirate** [comment]
更新git的submodule。

**Comment by JackTiger** [comment]
@blindpirate 当前我们发现在windows上执行gogradle解析时比较慢，主要耗时在依赖解析这块，从日志看，是分支解析这块的一些git操作比较慢，平均1个库的解析时间大概在10秒左右。
看了下主要是[git, fetch, --all, --progress]这个操作耗时5秒，其他git log, checkout也基本1-2秒。

所以这块我们想优化一下，从两个方便考虑：
1.windows上git操作速度优化(linux上操作的确非常快，毫秒级)
2.gogradle在解析依赖时使用多线程并发的方式执行git操作，当前的架构是否可以支持使用多线程的方式去并行执行(**考虑到存在冲突版本的场景，在线程中执行会有同一个库并行写入的风险**)

想咨询下你的建议，非常感谢！

**Comment by JackTiger** [comment]
@blindpirate 整个循环执行git操作的入口是在https://github.com/gogradle/gogradle/commit/45bfc4dd5d76b5e9a92533fa85aced8a4e9c9158#diff-11d8ddd942a7f750f05e2eafbe3e10bdR65 吗？

**Comment by blindpirate** [comment]
https://github.com/gogradle/gogradle/blob/45bfc4dd5d76b5e9a92533fa85aced8a4e9c9158/src/main/java/com/github/blindpirate/gogradle/core/dependency/tree/DependencyTreeFactory.java#L65

是解析整棵依赖树的入口，`解析`指的是将一个符号`github.com/a/b@1.0.0`解析为一个实际存在的git仓库版本号（及其传递性依赖）的过程，这其中可能会有git操作。依赖树的解析是BFS顺序，因此我认为同一层是可以并行解析的。

例如，我们有一个依赖包a，在未解析之前，a只是一个符号，我们不知道它对应哪个仓库的哪个版本，也不知道它包含哪些传递性依赖。解析之后，a被定位到一个事实存在的仓库的特定版本，并且我们通过分析得知它的传递性依赖是b和c。此时，a的解析就完成了，接下来分别进行b和c的解析（同样，此时b和c也只是一个符号）。显然，我们可以同时进行b和c的解析。并行化的主要风险在于对共享的`DependencyRegistry`的访问控制。

**Comment by JackTiger** [comment]
@blindpirate 
你好，咨询下，报下面的错是什么引起的，有什么定位手段没？我初步怀疑是循环依赖解析导致的

```
02:03:52.434 [null] [org.gradle.launcher.daemon.server.Daemon] 
02:03:52.434 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
02:03:52.434 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
02:03:52.434 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
02:03:52.435 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
02:03:52.435 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
02:03:52.435 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
02:03:52.435 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
02:04:02.434 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
02:04:02.434 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
02:04:02.434 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
02:04:02.435 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
02:04:02.435 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
02:04:02.435 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
02:04:02.436 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
02:04:12.434 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
02:04:12.434 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
02:04:12.434 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
02:04:12.435 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
02:04:12.435 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
02:04:12.435 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
02:04:12.435 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
02:04:22.434 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
```

**Comment by blindpirate** [comment]
我并没有看到任何的报错。哪一句是报错？

**Comment by JackTiger** [comment]
那一直报这个日志是在什么情况，因为我在构建解析依赖时，就一直卡在这，不继续往下？除非我把全局缓存中的对应的库删除了，才可以。

**Comment by blindpirate** [comment]
请使用`jstack`工具查看哪个线程卡在了什么地方。

**Comment by JackTiger** [comment]
https://github.com/gogradle/gogradle/issues/144 与这个问题比较像

**Comment by JackTiger** [comment]
@blindpirate 谢谢，我们使用jstack分析出来卡在下面有注释的位置(一直循环创建)：

```
private Session(VcsGolangPackage pkg) throws IOException {
     File lockFile = getMetadataPath(pkg);
     ensureDirExistAndWritable(lockFile.getParentFile().toPath());
     this.fileChannel = createLockFileIfNecessary(lockFile);
    
     this.fileLock = fileChannel.lock();//卡在这个函数，一直循环创建
    
     this.metadata = getMetadataFromFile(fileChannel).orElse(GlobalCacheMetadata.newMetadata(pkg));

     Optional<GolangRepositoryMetadata> matched = findMatchedRepository(metadata, 
     pkg.getRepository());
     if (!matched.isPresent()) {
           metadata.addRepository(pkg.getRepository());
           matched = findMatchedRepository(metadata, pkg.getRepository());
      }

      repositoryMetadata = matched.get();
      repoRoot = getRepoPath(pkg, repositoryMetadata.getDir());
}
```
this.fileLock = fileChannel.lock();
如果改成try catch的方式，立马就失败了。

```
---
package: "code.xxxxx.com/xxxxx/xxxx/xxxxx/xxxxxxx"
apiVersion: "0.10.0"
repositories:
- vcs: "git"
urls:
- "git@code.xxxxxxx.com:xxxxx/xxxx/xxxxx/xxxxxxx.git"
original: false
lastUpdatedTime: 1533777308335
dir: "0e7b6e8b4fde037f0aa05835b81753e6"
```

**Comment by JackTiger** [comment]
@blindpirate 现在出现这个问题的概率非常高，一有问题就直接挂死在这

**Comment by blindpirate** [comment]
你提供的信息太少，并且描述也不清楚，卡住我明白，但是什么叫“循环创建”？

请至少提供jstack的完整stacktrace，而非描述它卡在了哪里。

改成try catch的方式，立马失败，是怎么改的，try catch加在哪里？请不要用“改成try catch”这种描述，而是直接把修改后的代码写出来。我对你们的代码，这个问题的上下文一无所知，请不要假设我了解这个问题的背景。

另外，在卡住发生的时候，机器上是否有多个Gradle构建在同时进行？

最后，你可以在这个函数中多加一些日志，因为显然如果死锁了，那么一定有其他人锁住了此文件没有放开，增加日志会有助于发现并解决问题。

**Comment by JackTiger** [comment]
gogradle解析依赖时，卡在下面的位置，从日志看是挂死在下面的pb.start()这句代码中，执行时只有1个gradle，不清楚是什么原因导致的  @blindpirate 

```
public Process run(List<String> args, Map<String, String> envs, File workingDirectory) {
LOGGER.debug("Forking process: args {}, envs {}, workingDir {}", args, envs, workingDirectory);
try {
       ProcessBuilder pb = new ProcessBuilder().command(args);
       if (envs != null) {
           pb.environment().putAll(envs);
        }
       if (workingDirectory != null) {
             pb.directory(workingDirectory);
        }
       return pb.start();
    } catch (IOException e) {
       throw new UncheckedIOException(e);
    }  
}

```

```
11:49:15.101 [DEBUG] [com.github.blindpirate.gogradle.util.ProcessUtils] Forking process: args [git, for-each-ref, --sort=-creatordate, --format, %(objectname):%(refname:short):%(creatordate:raw), refs/tags], envs {}, workingDir C:\Users\xxxxxxx\.gradle\go\repo\xxxxx.xxxxxx.com\d32f97273ce25918fff6960386be3c73
11:49:17.612 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
11:49:17.613 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
11:49:17.613 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
11:49:17.618 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
11:49:17.619 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
11:49:17.619 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
11:49:17.620 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
11:49:27.612 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
11:49:27.613 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
11:49:27.613 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
11:49:27.615 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
11:49:27.616 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
11:49:27.616 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
11:49:27.618 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
11:49:37.613 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
11:49:37.614 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
11:49:37.614 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
11:49:37.615 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
11:49:37.616 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
11:49:37.616 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
11:49:37.617 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
11:49:47.613 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
11:49:47.615 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
11:49:47.615 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
11:49:47.616 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
11:49:47.618 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
11:49:47.618 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
11:49:47.619 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
```

**Comment by blindpirate** [comment]
`pb.start()`不是一个阻塞方法，线程不可能卡在这里，随便开一个jstack你都可以看到，线程阻塞的地方要么是`Object.wait/Unsafe.park()`这样的阻塞方法，要么是`read`这样的IO操作。我最后强调一边，请放原始的jstack结果上来，不要自己归纳总结！

**Comment by JackTiger** [comment]
@blindpirate 
$ jps
```
18608 Jps
14104 Launcher
5176 GradleWrapperMain
8776 GradleDaemon
```

$ jstack 5176
```
2018-08-30 09:37:38
Full thread dump Java HotSpot(TM) 64-Bit Server VM (25.144-b01 mixed mode):

"forward input" #16 prio=5 os_prio=0 tid=0x000000001a387000 nid=0x1b0 waiting on condition [0x000000001b80f000]
   java.lang.Thread.State: WAITING (parking)
        at sun.misc.Unsafe.park(Native Method)
        - parking to wait for  <0x00000000d5af8918> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
        at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
        at org.gradle.util.DisconnectableInputStream.read(DisconnectableInputStream.java:138)
        at org.gradle.launcher.daemon.client.InputForwarder$1.run(InputForwarder.java:77)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)

"DisconnectableInputStream source reader" #15 daemon prio=5 os_prio=0 tid=0x000000001a386800 nid=0x2150 runnable [0x000000001b91f000]
   java.lang.Thread.State: RUNNABLE
        at java.io.FileInputStream.readBytes(Native Method)
        at java.io.FileInputStream.read(FileInputStream.java:255)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
        - locked <0x00000000d7744190> (a java.io.BufferedInputStream)
        at org.gradle.util.DisconnectableInputStream$1.run(DisconnectableInputStream.java:96)
        at java.lang.Thread.run(Thread.java:748)

"Service Thread" #9 daemon prio=9 os_prio=0 tid=0x0000000018d14800 nid=0x28cc runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C1 CompilerThread2" #8 daemon prio=9 os_prio=2 tid=0x0000000018ca5800 nid=0x2e44 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread1" #7 daemon prio=9 os_prio=2 tid=0x0000000018ca4000 nid=0x3e40 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"C2 CompilerThread0" #6 daemon prio=9 os_prio=2 tid=0x000000001783b000 nid=0x15a8 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Attach Listener" #5 daemon prio=5 os_prio=2 tid=0x0000000017838000 nid=0x3220 waiting on condition [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Signal Dispatcher" #4 daemon prio=9 os_prio=2 tid=0x0000000017837000 nid=0x10a4 runnable [0x0000000000000000]
   java.lang.Thread.State: RUNNABLE

"Finalizer" #3 daemon prio=8 os_prio=1 tid=0x000000001781d000 nid=0x27dc in Object.wait() [0x000000001892e000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000000d7688c58> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:143)
        - locked <0x00000000d7688c58> (a java.lang.ref.ReferenceQueue$Lock)
        at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:164)
        at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:209)

"Reference Handler" #2 daemon prio=10 os_prio=2 tid=0x00000000177d6800 nid=0x5390 in Object.wait() [0x0000000018c7f000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        - waiting on <0x00000000d76902f0> (a java.lang.ref.Reference$Lock)
        at java.lang.Object.wait(Object.java:502)
        at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
        - locked <0x00000000d76902f0> (a java.lang.ref.Reference$Lock)
        at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)

"main" #1 prio=5 os_prio=0 tid=0x00000000027b8000 nid=0x3150 runnable [0x0000000002bcc000]
   java.lang.Thread.State: RUNNABLE
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296)
        at sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278)
        at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
        - locked <0x00000000d593b3a8> (a sun.nio.ch.Util$3)
        - locked <0x00000000d593b320> (a java.util.Collections$UnmodifiableSet)
        - locked <0x00000000d593af20> (a sun.nio.ch.WindowsSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
        at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:101)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketInputStream.read(SocketConnection.java:178)
        at com.esotericsoftware.kryo.io.Input.fill(Input.java:139)
        at com.esotericsoftware.kryo.io.Input.require(Input.java:159)
        at com.esotericsoftware.kryo.io.Input.readInt(Input.java:308)
        at org.gradle.internal.serialize.kryo.KryoBackedDecoder.readSmallInt(KryoBackedDecoder.java:120)
        at org.gradle.internal.serialize.DefaultSerializerRegistry$TaggedTypeSerializer.read(DefaultSerializerRegistry.java:139)
        at org.gradle.internal.serialize.Serializers$StatefulSerializerAdapter$1.read(Serializers.java:36)
        at org.gradle.internal.remote.internal.inet.SocketConnection.receive(SocketConnection.java:79)
        at org.gradle.launcher.daemon.client.DaemonClientConnection.receive(DaemonClientConnection.java:75)
        at org.gradle.launcher.daemon.client.DaemonClientConnection.receive(DaemonClientConnection.java:35)
        at org.gradle.launcher.daemon.client.DaemonClient.monitorBuild(DaemonClient.java:210)
        at org.gradle.launcher.daemon.client.DaemonClient.executeBuild(DaemonClient.java:178)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:141)
        at org.gradle.launcher.daemon.client.DaemonClient.execute(DaemonClient.java:92)
        at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
        at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:291)
        at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:264)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:33)
        at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
        at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:257)
        at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:191)
        at org.gradle.launcher.Main.doAction(Main.java:33)
        at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:60)
        at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:37)
        at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:31)
        at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:108)
        at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)

"VM Thread" os_prio=2 tid=0x00000000177ce800 nid=0x51dc runnable

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00000000027cd000 nid=0x3a8c runnable

"GC task thread#1 (ParallelGC)" os_prio=0 tid=0x00000000027ce800 nid=0x4784 runnable

"GC task thread#2 (ParallelGC)" os_prio=0 tid=0x00000000027d0000 nid=0x3698 runnable

"GC task thread#3 (ParallelGC)" os_prio=0 tid=0x00000000027d2000 nid=0x51f0 runnable

"VM Periodic Task Thread" os_prio=2 tid=0x0000000018d5c800 nid=0x4ab0 waiting on condition

JNI global references: 322

```

**Comment by blindpirate** [comment]
需要8776的结果，GradleWrapperMain只是一个和Daemon通信的客户端，真正的build过程发生在GradleDaemon的JVM进程中。

**Comment by blindpirate** [comment]
似乎是这个问题：https://stackoverflow.com/questions/5483830/process-waitfor-never-returns

我创建了一个PR：https://github.com/gogradle/gogradle/pull/243

**Comment by blindpirate** [comment]
不知道能否请你将 #243  cherry-pick到自己的分支上并试用一下，然后再反馈给我是否解决？

**Comment by JackTiger** [comment]
我刚使用cherry-pick MR到我们的分支上试用了下，可以解决问题。之前遇到的lock的问题，我们继续验证一下，看是不是都是这个问题引起的，谢谢！ @blindpirate

**Comment by JackTiger** [comment]
@blindpirate 

你好，咨询个问题
```
rootProject
      |
     A - C1
     B - C2
C1 > C2版本

使用gogradle执行下面两个任务，全局缓存中的C的库的版本会存在差异
执行 ./gradlew goLock或者./gradlew gD，任务执行结束后全局缓存中C的版本为C2

执行./gradlew goBuild或者./gradlew goVendor，任务执行结束后全局缓存中的C版本为C1

本地测试下来，即存在生成vendor的场景，全局缓存中的C的最终版本都为C1
```

上面的实现是故意如此，还是是个bug，谢谢！
