### ISSUE TITLE
Not able to resolve non-github library

### ISSUE THREAD

**Issue by JohnRoach** [gogradle/gogradle#236]
Hi the dependency below is resolving in error although the package is able to be brought in manually,

```
dependencies {
    golang {
        build(['name':'gopkg.in/alecthomas/kingpin.v2'])
    }
}
```

Exception:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':resolveBuildDependencies'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$ExecuteTaskAction.execute(DefaultTaskExecutionGraph.java:246)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:136)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.execute(DefaultTaskPlanExecutor.java:201)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.executeWithTask(DefaultTaskPlanExecutor.java:192)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: com.github.blindpirate.gogradle.core.exceptions.ResolutionStackWrappingException: Exception in resolution, message is:
Cannot recognize package: "gopkg.in/alecthomas/kingpin.v2
Resolution stack is:
+- github.com/johnroach/kafkaTester

        at com.github.blindpirate.gogradle.core.exceptions.ResolutionStackWrappingException.wrapWithResolutionStack(ResolutionStackWrappingException.java:51)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.resolve(DependencyTreeFactory.java:93)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.getTree(DependencyTreeFactory.java:44)
        at com.github.blindpirate.gogradle.task.ResolveDependencies.resolveDependencies(ResolveDependencies.java:172)
        at com.github.blindpirate.gogradle.task.ResolveDependencies.resolve(ResolveDependencies.java:153)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:794)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:761)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:317)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:309)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:185)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:97)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 30 more
Caused by: com.github.blindpirate.gogradle.core.exceptions.UnrecognizedPackageException: Cannot recognize package: "gopkg.in/alecthomas/kingpin.v2
        at com.github.blindpirate.gogradle.core.exceptions.UnrecognizedPackageException.cannotRecognizePackage(UnrecognizedPackageException.java:28)
        at com.github.blindpirate.gogradle.core.dependency.UnrecognizedNotationDependency.getTransitiveDepExclusions(UnrecognizedNotationDependency.java:51)
        at com.github.blindpirate.gogradle.core.dependency.ResolveContext.<init>(ResolveContext.java:72)
        at com.github.blindpirate.gogradle.core.dependency.ResolveContext.createSubContext(ResolveContext.java:55)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.createSubContextAndResolve(DependencyTreeFactory.java:101)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.lambda$resolve$0(DependencyTreeFactory.java:90)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.resolve(DependencyTreeFactory.java:91)
        ... 47 more
```

**Comment by blindpirate** [comment]
@JohnRoach can you please retry with `-i` parameter? That would print more detailed log. You might see some error which happens when Gogradle tried to access  `gopkg.in/alecthomas/kingpin.v2`.

**Comment by JohnRoach** [comment]
Sorry about this. For some reason, it is now working. Will close the ticket.

**Comment by blindpirate** [comment]
I guess it got a `Read time out` or something just now.

**Comment by JohnRoach** [comment]
Weird. Maybe a feature request would be to handle this error more gracefully?
