### ISSUE TITLE
Cannot found any files in .git/refs/heads

### ISSUE THREAD

**Issue by JackTiger** [gogradle/gogradle#257]
```
Caused by: java.lang.IllegalStateException: Cannot found any files in /root/.gradle/go/repo/xxxxx.xxx.xxx/xxx/xxx/xxx/xxx/7a79343d21d1fbef2637f21ff6614b5d/.git/refs/heads
	at com.github.blindpirate.gogradle.util.Assert.isTrue(Assert.java:30)
	at com.github.blindpirate.gogradle.util.Assert.isNotEmpty(Assert.java:54)
	at com.github.blindpirate.gogradle.vcs.git.GitClientAccessor.getDefaultBranch(GitClientAccessor.java:85)
	at com.github.blindpirate.gogradle.vcs.GitMercurialDependencyManager.determineVersion(GitMercurialDependencyManager.java:119)
	at com.github.blindpirate.gogradle.vcs.GitMercurialDependencyManager.determineVersion(GitMercurialDependencyManager.java:41)
	at com.github.blindpirate.gogradle.core.dependency.resolve.AbstractVcsDependencyManager.doResolve(AbstractVcsDependencyManager.java:67)
```

这种是什么情况会导致.git/refs/heads文件夹为空

**Comment by blindpirate** [comment]
不知道。如果这种情况频繁发生的话，似乎应该fetch并重试。
