### ISSUE TITLE
GoGradle defaults to Bazaar VCS when parsing dependencies

### ISSUE THREAD

**Issue by bejelith** [gogradle/gogradle#264]
Im trying to build with an influxdb dependency and i get this exception when gogradle checkouts the repository
Im testing with gogradle '0.10.2'

**Cannot resolve dependency:github.com/influxdb/influxdb/client: commit='afde71eb1740fd763ab9450e1f700ba0e53c36d0', urls=[git@github.com:influxdata/influxdb.git]**

**Caused by: java.lang.UnsupportedOperationException: Bazaar support is under development now!**

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':resolveBuildDependencies'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: com.github.blindpirate.gogradle.core.exceptions.ResolutionStackWrappingException: Exception in resolution, message is:
Cannot resolve dependency:github.com/influxdb/influxdb/client: commit='afde71eb1740fd763ab9450e1f700ba0e53c36d0', urls=[git@github.com:influxdata/influxdb.git]
Resolution stack is:
+- vitess.io/vitess

        at com.github.blindpirate.gogradle.core.exceptions.ResolutionStackWrappingException.wrapWithResolutionStack(ResolutionStackWrappingException.java:51)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.resolve(DependencyTreeFactory.java:93)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.getTree(DependencyTreeFactory.java:44)
        at com.github.blindpirate.gogradle.task.ResolveDependencies.resolveDependencies(ResolveDependencies.java:172)
        at com.github.blindpirate.gogradle.task.ResolveDependencies.resolve(ResolveDependencies.java:153)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 31 more
Caused by: com.github.blindpirate.gogradle.core.exceptions.DependencyResolutionException: Cannot resolve dependency:github.com/influxdb/influxdb/client: commit='afde71eb1740fd763ab9450e1f700ba0e53c36d0', urls=[git@github.com:influxdata/influxdb.git]
        at com.github.blindpirate.gogradle.core.exceptions.DependencyResolutionException.cannotResolveDependency(DependencyResolutionException.java:56)
        at com.github.blindpirate.gogradle.core.dependency.resolve.AbstractVcsDependencyManager.doResolve(AbstractVcsDependencyManager.java:73)
        at com.github.blindpirate.gogradle.core.dependency.resolve.CacheEnabledDependencyResolverMixin.lambda$resolve$0(CacheEnabledDependencyResolverMixin.java:38)
        at com.github.blindpirate.gogradle.core.cache.CloneBackedCache.get(CloneBackedCache.java:34)
        at com.github.blindpirate.gogradle.core.cache.ProjectCacheManager.resolve(ProjectCacheManager.java:59)
        at com.github.blindpirate.gogradle.core.dependency.resolve.CacheEnabledDependencyResolverMixin.resolve(CacheEnabledDependencyResolverMixin.java:36)
        at com.github.blindpirate.gogradle.vcs.git.GitNotationDependency.doResolve(GitNotationDependency.java:28)
        at com.github.blindpirate.gogradle.core.dependency.AbstractNotationDependency.resolve(AbstractNotationDependency.java:55)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.createSubContextAndResolve(DependencyTreeFactory.java:102)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.lambda$resolve$0(DependencyTreeFactory.java:90)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.resolve(DependencyTreeFactory.java:91)
        ... 48 more
Caused by: java.lang.UnsupportedOperationException: Bazaar support is under development now!
        at com.github.blindpirate.gogradle.vcs.bazaar.BazaarNotationConverter.convert(BazaarNotationConverter.java:28)
        at com.github.blindpirate.gogradle.core.dependency.parse.DefaultNotationConverter.convert(DefaultNotationConverter.java:49)
        at com.github.blindpirate.gogradle.util.logging.DebugLogMethodInterceptor.invoke(DebugLogMethodInterceptor.java:38)
        at com.github.blindpirate.gogradle.core.dependency.parse.DefaultNotationParser.convertToMap(DefaultNotationParser.java:48)
        at com.github.blindpirate.gogradle.core.dependency.parse.DefaultNotationParser.parse(DefaultNotationParser.java:42)
        at com.github.blindpirate.gogradle.core.dependency.produce.SourceCodeDependencyFactory.createDependencies(SourceCodeDependencyFactory.java:88)
        at com.github.blindpirate.gogradle.core.dependency.produce.SourceCodeDependencyFactory.produce(SourceCodeDependencyFactory.java:72)
        at com.github.blindpirate.gogradle.core.dependency.produce.DefaultDependencyVisitor.visitSourceCodeDependencies(DefaultDependencyVisitor.java:87)
        at com.github.blindpirate.gogradle.util.logging.DebugLogMethodInterceptor.invoke(DebugLogMethodInterceptor.java:38)
        at com.github.blindpirate.gogradle.core.dependency.produce.strategy.DefaultDependencyProduceStrategy.visitAll(DefaultDependencyProduceStrategy.java:64)
        at com.github.blindpirate.gogradle.core.dependency.produce.strategy.DefaultDependencyProduceStrategy.produce(DefaultDependencyProduceStrategy.java:46)
        at com.github.blindpirate.gogradle.core.dependency.ResolveContext.lambda$produceTransitiveDependencies$0(ResolveContext.java:83)
        at com.github.blindpirate.gogradle.core.cache.CloneBackedCache.get(CloneBackedCache.java:34)
        at com.github.blindpirate.gogradle.core.cache.ProjectCacheManager.produce(ProjectCacheManager.java:68)
        at com.github.blindpirate.gogradle.core.dependency.ResolveContext.produceTransitiveDependencies(ResolveContext.java:82)
        at com.github.blindpirate.gogradle.vcs.GitMercurialDependencyManager.createResolvedDependency(GitMercurialDependencyManager.java:69)
        at com.github.blindpirate.gogradle.vcs.GitMercurialDependencyManager.createResolvedDependency(GitMercurialDependencyManager.java:41)
        at com.github.blindpirate.gogradle.core.dependency.resolve.AbstractVcsDependencyManager.doResolve(AbstractVcsDependencyManager.java:71)
        ... 57 more
```

**Comment by bejelith** [comment]
I tested back until 0.8 and always got the issue, is it possible https://github.com/gogradle/gogradle/commit/d5899d964a6034ed6b7890b2e10d862b2001e99c tries to fix this?

**Comment by blindpirate** [comment]
Sorry for the delay, I was out of office in past several days. Here's what happened:

`vitess.io/vitess` references a pretty old version `influxdb`: https://github.com/vitessio/vitess/blob/master/vendor/vendor.json#L624

This version of `influxdb` has no dependency management file (because it's back to 2014) so gogradle starts analyzing its source code to find out all transitive dependencies. The `influxdb` code contains `launchpad.net/gocheck`, which is a bazaar-managed dependency. So all behaviours are expected. 

How about declaring a newer version of influxdb in the `build.gradle` file?

**Comment by blindpirate** [comment]
Try `build name: 'vitess.io/vitess', transitive: false`

**Comment by bejelith** [comment]
> Try build name: 'vitess.io/vitess', transitive: false

Will try this, thanks!
