### ISSUE TITLE
etcd dependency creates near infinite vendor folder hierarchy

### ISSUE THREAD

**Issue by Tarkleigh** [gogradle/gogradle#274]
I am using Gogradle to build a Go project depending on the [Gardener](https://github.com/gardener/gardener/tree/0.13.2) project (the command used in my build.gradle is “build 'github.com/gardener/gardener@0.13.2'”). Gardener in turn uses etcd release [3.2.24](https://github.com/etcd-io/etcd/tree/v3.2.24), which causes Gogradle to install etcd into my vendor folder as a transitive dependency. In general, this would be fine but etcd includes a symbolic link onto itself in the **“cmd”** folder, causing Gogradle to build a near infinite folder structure within my vendor folder. While the build finishes eventually, this folder structure causes problems with certain other tools in my toolchain.

Is there any way I can tell Gogradle not to create such a deep structure? I had a look at issue #216  (using Google translate, so my understanding might not be perfect) and this seems like a similar problem. I followed the suggestion there and tried setting `core.symlinks=false` in Git but this did not seem to make a difference. The problem occurs with both Gogradle 0.10.2 and 0.10.3

By the way, thanks for all you hard work, I much prefer Gogradle to Dep, I just wish etcd did not include this link in their project :)

**Comment by blindpirate** [comment]
Thanks for reporting, this is definitely a bug. I believe it's fixed in 0.11, can you please try it out?

**Comment by Tarkleigh** [comment]
Thanks for the quick fix. I would love to test it out but it seems like my build.gradle is not working anymore with 0.11. When I try to execute any command, it fails with the error `Could not find method build() for arguments [build_693etl253rgal6bl7c0ls083s$_run_closure2@416a68f8] on root project 'eps-k8s' of type org.gradle.api.Project.` 

I suspect this has something to do with my dependencies which are currently defined like this:
```dependencies {
    golang {
        build 'github.com/gardener/gardener@0.13.2'
        build 'k8s.io/client-go@kubernetes-1.12.1'
        build 'github.com/gorilla/mux@v1.6.2'
        build 'github.com/pkg/errors@v0.8.0'
        build 'github.com/sirupsen/logrus@v1.2.0'
        build 'github.com/coreos/go-semver@0.2.0'
        build 'github.com/coreos/go-oidc@v2.0.0'

        test 'github.com/stretchr/testify@v1.2.2'
        test 'github.com/golang/mock@v1.1.1'
    }    
}
```

Do I have to change the build.gradle for the new version? I checked the docs and there does not seem to be a new format there. I tried renaming the task to GoDependencies but it did not seem to make a difference.

**Comment by blindpirate** [comment]
Can you please paste more of your `build.gradle`? It's somewhat truncated. Also, please let me know your gradle version.

**Comment by Tarkleigh** [comment]
Gladly, this would be the whole json (except the auto-generated comments)

```
plugins {
    id 'com.github.blindpirate.gogradle' version '0.11'
}

golang {
    goVersion = '1.11.2'
    packagePath = 'github.wdf.sap.corp/k8s-cp-integration/eps-k8s' // go import path be built, NOT local file system path!
}
build {
    String executableName
    if (System.properties['os.name'].toLowerCase().contains('windows')) {
        executableName = "eps-main.exe"
    } else {
        executableName = "eps-main"
    }
    String buildCommand = "build -o " + executableName + " " + "github.wdf.sap.corp/k8s-cp-integration/eps-k8s/src"
    go buildCommand
}

dependencies {
    golang {
        build 'github.com/gardener/gardener@0.13.2'
        build 'k8s.io/client-go@kubernetes-1.12.1'
        build 'github.com/gorilla/mux@v1.6.2'
        build 'github.com/pkg/errors@v0.8.0'
        build 'github.com/sirupsen/logrus@v1.2.0'
        build 'github.com/coreos/go-semver@0.2.0'
        build 'github.com/coreos/go-oidc@v2.0.0'

        test 'github.com/stretchr/testify@v1.2.2'
        test 'github.com/golang/mock@v1.1.1'
    }    
}
```
I tested it with both my local Gradle (which would be 4.10.2) and the current packaged version of Gradle (with Gradlew.bat) which uses 5.0, I'm using Windows 10

**Comment by blindpirate** [comment]
```
build {  // <------ this is the problem
    String executableName
    if (System.properties['os.name'].toLowerCase().contains('windows')) {
        executableName = "eps-main.exe"
    } else {
        executableName = "eps-main"
    }
    String buildCommand = "build -o " + executableName + " " + "github.wdf.sap.corp/k8s-cp-integration/eps-k8s/src"
    go buildCommand
}
```

Please rename `build` to `goBuild`. Since Gradle 5.0, plugins are not allowed to create tasks with name `build` anymore, so it's renamed as `goBuild`. Sorry for the inconvenience.

**Comment by Tarkleigh** [comment]
Thanks, this seems to have helped somewhat. Unfortunately, after I renamed the step, I now get an exception which seems to be internal:
` java.lang.NoSuchMethodError: java.nio.ByteBuffer.position(I)Ljava/nio/ByteBuffer;
        at com.github.blindpirate.gogradle.util.IOUtils.toByteArray(IOUtils.java:128)
        at com.github.blindpirate.gogradle.core.cache.DefaultGlobalCacheManager.getMetadataFromFile(DefaultGlobalCacheManager.java:244)
)`

I omited most of the stacktrace since it would blow up the formating. Give a shout if you need more information. By the way, I am using Java 8 could this be a problem?

**Comment by blindpirate** [comment]
Ah f*k... I'm bitten by this issue again... it's a compatibility issue of JDK 9, when the code is compiled by JDK 9+ but run on JDK8, this issue would occur: https://github.com/gradle/gradle/blob/4157aa6e60f9c6da5f03ae818e63d68315df0c1d/subprojects/base-services/src/main/java/org/gradle/internal/io/BufferCaster.java#L24

I'll release a `0.11.1` to fix it.

**Comment by blindpirate** [comment]
Released 0.11.1. Thanks for reporting!
