### ISSUE TITLE
gogradle运行显示java.nio.file.FileSystemException: 客户端没有所需的特权 （win10）

### ISSUE THREAD

**Issue by zhaoying818** [gogradle/gogradle#294]
E:\Go\examples\typical-build> .\gradlew gB -iS
Initialized native services in: C:\Users\zhaoying\.gradle\native
The client will now receive all logging from the daemon (pid: 11836). The daemon log file: C:\Users\zhaoying\.gradle\daemon\4.4\daemon-11836.out.log
Starting 9th build in daemon [uptime: 37 mins 37.253 secs, performance: 99%, no major garbage collections]
Using 4 worker leases.
Creating new cache for fileHashes, path E:\Go\examples\typical-build\.gradle\4.4\fileHashes\fileHashes.bin, access org.gradle.cache.internal.DefaultCacheAccess@186e529
Starting Build
Settings evaluated using settings file 'E:\Go\examples\typical-build\settings.gradle'.
Projects loaded. Root project using build file 'E:\Go\examples\typical-build\build.gradle'.
Included projects: [root project 'typical-build']

> Configure project :
Evaluating root project 'typical-build' using build file 'E:\Go\examples\typical-build\build.gradle'.
Creating new cache for metadata-1.1/results, path C:\Users\zhaoying\.gradle\caches\transforms-1\metadata-1.1\results.bin, access org.gradle.cache.internal.DefaultCacheAccess@17eb94a
Creating new cache for metadata-2.36/module-metadata, path C:\Users\zhaoying\.gradle\caches\modules-2\metadata-2.36\module-metadata.bin, access org.gradle.cache.internal.DefaultCacheAccess@172c5d
Creating new cache for metadata-2.36/module-artifacts, path C:\Users\zhaoying\.gradle\caches\modules-2\metadata-2.36\module-artifacts.bin, access org.gradle.cache.internal.DefaultCacheAccess@172c5d
Creating new cache for metadata-2.36/module-artifact, path C:\Users\zhaoying\.gradle\caches\modules-2\metadata-2.36\module-artifact.bin, access org.gradle.cache.internal.DefaultCacheAccess@172c5d
Found go 1.12.4 in D:\Go\bin\go.exe, use it.
Ignore packages globally: appengine,a,gen,shared,common,thrifttest,appengine_internal,thrift,tutorial

All projects evaluated.
Selected primary task 'goBuild' from project :
Tasks to be executed: [task ':goPrepare', task ':resolveBuildDependencies', task ':resolveTestDependencies', task ':installDependencies', task ':buildWindows386', task ':goVendor', task ':goTest', task ':goCover', task ':goVet', task ':gofmt', task ':goCheck', task ':goBuild']
Creating new cache for resourceHashesCache, path E:\Go\examples\typical-build\.gradle\4.4\fileHashes\resourceHashesCache.bin, access org.gradle.cache.internal.DefaultCacheAccess@186e529
Creating new cache for taskHistory, path E:\Go\examples\typical-build\.gradle\4.4\taskHistory\taskHistory.bin, access org.gradle.cache.internal.DefaultCacheAccess@18f111b
Creating new cache for outputFiles, path E:\Go\examples\typical-build\.gradle\buildOutputCleanup\outputFiles.bin, access org.gradle.cache.internal.DefaultCacheAccess@173c551
:goPrepare (Thread[Task worker for ':',5,main]) started.

> Task :goPrepare FAILED
Putting task artifact state for task ':goPrepare' into context took 0.0 secs.
Up-to-date check for task ':goPrepare' took 0.0 secs. It is not up-to-date because:
  Task has not declared any outputs.

:goPrepare (Thread[Task worker for ':',5,main]) completed. Took 0.001 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':goPrepare'.
> Create symbolic link at E:\Go\examples\typical-build\.gogradle\project_gopath\src\github.com\my\package failed

* Try:
Run with --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':goPrepare'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:745)
Caused by: com.github.blindpirate.gogradle.core.exceptions.BuildException: Create symbolic link at E:\Go\examples\typical-build\.gogradle\project_gopath\src\github.com\my\package failed
        at com.github.blindpirate.gogradle.core.exceptions.BuildException.cannotCreateSymbolicLink(BuildException.java:41)
        at com.github.blindpirate.gogradle.build.DefaultBuildManager.createSymbolicLink(DefaultBuildManager.java:144)
        at com.github.blindpirate.gogradle.build.DefaultBuildManager.createProjectSymbolicLinkIfNotExist(DefaultBuildManager.java:136)
        at com.github.blindpirate.gogradle.build.DefaultBuildManager.prepareProjectGopathIfNecessary(DefaultBuildManager.java:105)
        at com.github.blindpirate.gogradle.task.GoPrepare.prepare(GoPrepare.java:59)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:780)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:747)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
        ... 32 more
_Caused by: java.nio.file.FileSystemException: E:\Go\examples\typical-build\.gogradle\project_gopath\src\github.com\my\package: 客户端没有所需的特权。_

        at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
        at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
        at sun.nio.fs.WindowsFileSystemProvider.createSymbolicLink(WindowsFileSystemProvider.java:585)
        at java.nio.file.Files.createSymbolicLink(Files.java:1043)
        at com.github.blindpirate.gogradle.build.DefaultBuildManager.createSymbolicLink(DefaultBuildManager.java:142)
        ... 52 more

* Get more help at https://help.gradle.org

**Comment by blindpirate** [comment]
https://github.com/gogradle/gogradle/blob/master/docs/faq-cn.md#%E5%9C%A8windows%E4%B8%8B%E5%A6%82%E4%BD%95%E5%A4%84%E7%90%86javaniofilefilesystemexception-a-required-privilege-is-not-held-by-the-client
