### ISSUE TITLE
gradle build failed for task resolvedeependencies

### ISSUE THREAD

**Issue by priyankasahoo01** [gogradle/gogradle#299]
getting below error in running gradle build.
from build.gradle:
dependencies {
        classpath "gradle.plugin.com.github.blindpirate:gogradle:0.7.0"
    }

apply plugin: "com.github.blindpirate.gogradle"

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':resolveBuildDependencies'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: com.github.blindpirate.gogradle.core.exceptions.ResolutionStackWrappingException: Exception in resolution, message is:
Cannot resolve dependency:github.com/emicklei/go-restful: commit='LATEST_COMMIT', urls=[git@github3.cisco.com:tesseract-jenkin-gen/godep-gh-emicklei-go-restful.git]
Resolution stack is:

        at com.github.blindpirate.gogradle.core.exceptions.ResolutionStackWrappingException.wrapWithResolutionStack(ResolutionStackWrappingException.java:51)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.resolve(DependencyTreeFactory.java:85)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.getTree(DependencyTreeFactory.java:40)
        at com.github.blindpirate.gogradle.task.ResolveDependencies.resolveDependencies(ResolveDependencies.java:171)
        at com.github.blindpirate.gogradle.task.ResolveDependencies.resolve(ResolveDependencies.java:152)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 31 more
Caused by: com.github.blindpirate.gogradle.core.exceptions.DependencyResolutionException: Cannot resolve dependency:github.com/emicklei/go-restful: commit='LATEST_COMMIT', urls=[git@github3.dummy.com:tesseract-jenkin-gen/godep-gh-emicklei-go-restful.git]
        at com.github.blindpirate.gogradle.core.exceptions.DependencyResolutionException.cannotResolveDependency(DependencyResolutionException.java:56)
        at com.github.blindpirate.gogradle.core.dependency.resolve.AbstractVcsDependencyManager.doResolve(AbstractVcsDependencyManager.java:69)
        at com.github.blindpirate.gogradle.core.dependency.resolve.CacheEnabledDependencyResolverMixin.lambda$resolve$0(CacheEnabledDependencyResolverMixin.java:38)
        at com.github.blindpirate.gogradle.core.cache.CloneBackedCache.get(CloneBackedCache.java:34)
        at com.github.blindpirate.gogradle.core.cache.ProjectCacheManager.resolve(ProjectCacheManager.java:57)
        at com.github.blindpirate.gogradle.core.dependency.resolve.CacheEnabledDependencyResolverMixin.resolve(CacheEnabledDependencyResolverMixin.java:36)
        at com.github.blindpirate.gogradle.vcs.git.GitNotationDependency.doResolve(GitNotationDependency.java:28)
        at com.github.blindpirate.gogradle.core.dependency.AbstractNotationDependency.resolve(AbstractNotationDependency.java:55)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.createSubContextAndResolve(DependencyTreeFactory.java:92)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.lambda$resolve$0(DependencyTreeFactory.java:77)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.resolve(DependencyTreeFactory.java:78)
        ... 48 more
Caused by: com.github.blindpirate.gogradle.core.exceptions.DependencyResolutionException: Cloning repository of github.com/emicklei/go-restful failed.
        at com.github.blindpirate.gogradle.core.exceptions.DependencyResolutionException.cannotCloneRepository(DependencyResolutionException.java:39)
        at com.github.blindpirate.gogradle.vcs.GitMercurialDependencyManager.tryCloneWithUrls(GitMercurialDependencyManager.java:184)
        at com.github.blindpirate.gogradle.vcs.GitMercurialDependencyManager.initRepository(GitMercurialDependencyManager.java:165)
        at com.github.blindpirate.gogradle.core.dependency.resolve.AbstractVcsDependencyManager.resolveRepository(AbstractVcsDependencyManager.java:130)
        at com.github.blindpirate.gogradle.core.dependency.resolve.AbstractVcsDependencyManager.resolveVcs(AbstractVcsDependencyManager.java:74)
        at com.github.blindpirate.gogradle.core.dependency.resolve.AbstractVcsDependencyManager.lambda$doResolve$0(AbstractVcsDependencyManager.java:66)
        at com.github.blindpirate.gogradle.core.cache.DefaultGlobalCacheManager.runWithGlobalCacheLock(DefaultGlobalCacheManager.java:148)
        at com.github.blindpirate.gogradle.core.dependency.resolve.AbstractVcsDependencyManager.doResolve(AbstractVcsDependencyManager.java:64)
        ... 57 more

**Comment by priyankasahoo01** [comment]
I tried upgrading the version as well
 dependencies {
        classpath "gradle.plugin.com.github.blindpirate:gogradle:0.11.3"
    }


But after this , I started facing below error:


A problem occurred evaluating root project 'myroguego'.
> Could not find method build() for arguments [build_10q4kgdxnndnew6g6jq79buav$_run_closure2@609a5efc] on root project 'myroguego' of type org.gradle.api.Project.

Caused by: org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method build() for arguments [build_10q4kgdxnndnew6g6jq79buav$_run_closure2@609a5efc] on root project 'myroguego' of type org.gradle.api.Project.
        at org.gradle.internal.metaobject.AbstractDynamicObject.methodMissingException(AbstractDynamicObject.java:179)
        at org.gradle.groovy.scripts.BasicScript$ScriptDynamicObject.methodMissingException(BasicScript.java:160)
        at org.gradle.internal.metaobject.AbstractDynamicObject.invokeMethod(AbstractDynamicObject.java:164)
        at org.gradle.groovy.scripts.BasicScript.invokeMethod(BasicScript.java:82)
        at build_10q4kgdxnndnew6g6jq79buav.run(/Users/priysaho/go/src/apps/myroguego/build.gradle:19)
        at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:90)
        ... 102 more



from build.gradle:
15 golang {
 16     packagePath = 'cisco.com/myroguego'
 17 }
 18 
 19 build {
 20     targetPlatform = ['darwin-amd64', 'linux-amd64']
 21 }
 22

**Comment by blindpirate** [comment]
Since Gradle 5.0 `build` is no longer a valid task name. Use `goBuild` instead:

```
goBuild {
    targetPlatform = ['darwin-amd64', 'linux-amd64']
}
```

**Comment by priyankasahoo01** [comment]
mine is gradle 4.10.2
(maglev3.5) PRIYSAHO-M-R0RL:myroguego priysaho$ gradle --version

------------------------------------------------------------
Gradle 4.10.2
------------------------------------------------------------

Build time:   2018-09-19 18:10:15 UTC
Revision:     b4d8d5d170bb4ba516e88d7fe5647e2323d791dd

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_201 (Oracle Corporation 25.201-b09)
OS:           Mac OS X 10.14.1 x86_64

**Comment by priyankasahoo01** [comment]
Well, I tried making change as suggested by you.  But then this is what I get:
 Exception is:
org.gradle.execution.TaskSelectionException: Task 'build' is ambiguous in root project 'myroguego'. Candidates are: 'buildDarwinAmd64', 'buildEnvironment', 'buildLinuxAmd64'.
        at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:116)


Note: I am new to gradle and go.

**Comment by priyankasahoo01** [comment]
Also, please confirm if I am using the right version for blindpirate:gogradle? which 0.11.3

**Comment by priyankasahoo01** [comment]
> Since Gradle 5.0 `build` is no longer a valid task name. Use `goBuild` instead:
> 
> ```
> goBuild {
>     targetPlatform = ['darwin-amd64', 'linux-amd64']
> }
> ```
I am using gradle 4.10.2

**Comment by priyankasahoo01** [comment]
This time I ran with 
gradle buildDarwinAmd64 --s
Again it started complaining about the same issue for resolveBuildDependencies task. Stacktrace:

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':resolveBuildDependencies'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: com.github.blindpirate.gogradle.core.exceptions.ResolutionStackWrappingException: Exception in resolution, message is:
Cannot resolve dependency:github.com/emicklei/go-restful: commit='LATEST_COMMIT', urls=[git@github3.cisco.com:tesseract-jenkin-gen/godep-gh-emicklei-go-restful.git]
Resolution stack is:
+- cisco.com/myroguego

        at com.github.blindpirate.gogradle.core.exceptions.ResolutionStackWrappingException.wrapWithResolutionStack(ResolutionStackWrappingException.java:51)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.resolve(DependencyTreeFactory.java:93)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.getTree(DependencyTreeFactory.java:44)
        at com.github.blindpirate.gogradle.task.ResolveDependencies.resolveDependencies(ResolveDependencies.java:170)
        at com.github.blindpirate.gogradle.task.ResolveDependencies.resolve(ResolveDependencies.java:151)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 31 more
Caused by: com.github.blindpirate.gogradle.core.exceptions.DependencyResolutionException: Cannot resolve dependency:github.com/emicklei/go-restful: commit='LATEST_COMMIT', urls=[git@github3.cisco.com:tesseract-jenkin-gen/godep-gh-emicklei-go-restful.git]
        at com.github.blindpirate.gogradle.core.exceptions.DependencyResolutionException.cannotResolveDependency(DependencyResolutionException.java:56)
        at com.github.blindpirate.gogradle.core.dependency.resolve.AbstractVcsDependencyManager.doResolve(AbstractVcsDependencyManager.java:73)
        at com.github.blindpirate.gogradle.core.dependency.resolve.CacheEnabledDependencyResolverMixin.lambda$resolve$0(CacheEnabledDependencyResolverMixin.java:38)
        at com.github.blindpirate.gogradle.core.cache.CloneBackedCache.get(CloneBackedCache.java:34)
        at com.github.blindpirate.gogradle.core.cache.ProjectCacheManager.resolve(ProjectCacheManager.java:57)
        at com.github.blindpirate.gogradle.core.dependency.resolve.CacheEnabledDependencyResolverMixin.resolve(CacheEnabledDependencyResolverMixin.java:36)
        at com.github.blindpirate.gogradle.vcs.git.GitNotationDependency.doResolve(GitNotationDependency.java:28)
        at com.github.blindpirate.gogradle.core.dependency.AbstractNotationDependency.resolve(AbstractNotationDependency.java:55)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.createSubContextAndResolve(DependencyTreeFactory.java:102)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.lambda$resolve$0(DependencyTreeFactory.java:90)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.resolve(DependencyTreeFactory.java:91)
        ... 48 more
Caused by: java.nio.channels.OverlappingFileLockException
        at com.github.blindpirate.gogradle.core.cache.DefaultGlobalCacheManager$Session.<init>(DefaultGlobalCacheManager.java:83)
        at com.github.blindpirate.gogradle.core.cache.DefaultGlobalCacheManager$Session.<init>(DefaultGlobalCacheManager.java:71)
        at com.github.blindpirate.gogradle.core.cache.DefaultGlobalCacheManager.startSession(DefaultGlobalCacheManager.java:137)
        at com.github.blindpirate.gogradle.core.dependency.resolve.AbstractVcsDependencyManager.doResolve(AbstractVcsDependencyManager.java:61)
        ... 57 more

from build.gradle:
    dependencies {
        classpath "gradle.plugin.com.github.blindpirate:gogradle:0.11.3"
    }
}

apply plugin: "com.github.blindpirate.gogradle"

golang {
    packagePath = 'cisco.com/myroguego'
}

goBuild {
    targetPlatform = ['darwin-amd64', 'linux-amd64']
}

**Comment by blindpirate** [comment]
> Well, I tried making change as suggested by you. But then this is what I get:
Exception is:
org.gradle.execution.TaskSelectionException: Task 'build' is ambiguous in root project 'myroguego'. Candidates are: 'buildDarwinAmd64', 'buildEnvironment', 'buildLinuxAmd64'.
at org.gradle.execution.TaskSelector.getSelection(TaskSelector.java:116)

Change to `goBuild` then run `gradle goBuild`, not `gradle build`.

>> Since Gradle 5.0 `build` is no longer a valid task name. Use `goBuild` instead:
>> 
>> ```
>> goBuild {
>>     targetPlatform = ['darwin-amd64', 'linux-amd64']
>> }
>> ```
> I am using gradle 4.10.2

What I'm saying is, since Gradle 5.0 `build` is no longer a valid task name, to support Gradle 5.0, we change the task name from `build` to `goBuild`. Not no matter which gradle version you're using, `build` task doesn't exist.

Also, can you format your code a little bit by using ```? It's too hard to look at.

**Comment by priyankasahoo01** [comment]
It worked. Thanks for your help.
