### ISSUE TITLE
go build tags

### ISSUE THREAD

**Issue by JackTiger** [gogradle/gogradle#97]
`CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags "-w -s" -o bfs .`

类似于这样的命令，我该如何添加

**Comment by blindpirate** [comment]
```
task myTask(type: Go) {
    enviroment([CGO_ENABLED:'0',GOOS:'linux'])
    doLast {
         go 'build -a -installsuffix cgo -ldflags "-w -s" -o bfs .'
    }
}
```

**Comment by JackTiger** [comment]
```
goBuild {
  enviroment([CGO_ENABLED:'0',GOOS:'linux'])
  doLast {
    go 'build -a -installsuffix cgo -ldflags "-w -s" -o bfs .'
  }
}
```

这样可以吗？

**Comment by blindpirate** [comment]
这样会有问题，在goBuild任务中，`GOOS`环境变量是内部控制的，不受environment影响

**Comment by JackTiger** [comment]
Could not find method enviroment() for arguments [{CGO_ENABLED=0, GOOS=linux}] on task ':myTask' of type com.github.blindpirate.gogradle.Go.

报错了

**Comment by JackTiger** [comment]
我发现一个问题，分支多了后，会导致：(重新编译就没有问题了，遇到好几次了)

```
Caused by: com.github.blindpirate.gogradle.core.exceptions.BuildException: Build failed due to exception of cmd: git pull --all --progress
in: /root/.gradle/go/gopath/code.xxxxx.com/xxxxx/prototype
with env:
 PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go:/usr/local/go/bin:/home/golang/bin
exception:com.github.blindpirate.gogradle.core.exceptions.BuildException: Build failed due to return code 1 of cmd: git pull --all --progress
in: /root/.gradle/go/gopath/code.xxxxx.com/xxxxxx/prototype
stderr: From code.xxxx.com:xxxxxxx/prototype
 * [new branch]      xxxxxx/soc -> origin/xxxxx/soc
   2c6844d..417f771  develop    -> origin/develop
error: cannot lock ref 'refs/remotes/origin/xxxxxx/funcSend': 'refs/remotes/origin/xxxxx' exists; cannot create 'refs/remotes/origin/xxxxx/funcSend'
 ! [new branch]      xxxxx/funcSend -> origin/xxxxx/funcSend  (unable to update local ref)
 * [new tag]         v0.2.0     -> v0.2.0
error: some local refs could not be updated; try running
 'git remote prune origin' to remove any old, conflicting branches
error: Could not fetch origin
```

**Comment by blindpirate** [comment]
如果问题一直发生在这个仓库里，可能是这个仓库有点问题，试试`git gc`，参考[这里](http://stackoverflow.com/questions/2998832/git-pull-fails-unable-to-resolve-reference-unable-to-update-local-ref)

**Comment by JackTiger** [comment]
```
error: cannot lock ref 'refs/remotes/origin/xxxx/funcSend': 'refs/remotes/origin/xxxx' exists; cannot create 'refs/remotes/origin/xxxx/funcSend'
 ! [new branch]      xxxx/funcSend -> origin/xxxx/funcSend  (unable to update local ref)
 * [new branch]      xxxxx_cellframe -> origin/xxxxx_cellframe
 * [new branch]      xxxxxcellframe -> origin/xxxxcellframe
 * [new branch]      xxxxfuncsend -> origin/xxxxfuncsend
 * [new branch]      xxxxsend -> origin/xxxxsend
 * [new branch]      xxxx/cellframe -> origin/xxxx/cellframe
error: some local refs could not be updated; try running
 'git remote prune origin' to remove any old, conflicting branches
error: Could not fetch origin
```

这种问题跟之前是同一类吗，感觉有问题

**Comment by JackTiger** [comment]
报 java.lang.UnsupportedOperationException (no error message)这个问题，一般是什么引起的？

**Comment by JackTiger** [comment]
```
Caused by: java.lang.UnsupportedOperationException
        at com.github.blindpirate.gogradle.core.dependency.GogradleRootProject.getUpdateTime(GogradleRootProject.java:51)
        at com.github.blindpirate.gogradle.core.dependency.DefaultDependencyRegistry.existentDependencyIsOutOfDate(DefaultDependencyRegistry.java:84)
        at com.github.blindpirate.gogradle.core.dependency.DefaultDependencyRegistry.register(DefaultDependencyRegistry.java:56)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.resolve(DependencyTreeFactory.java:67)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.lambda$resolve$1(DependencyTreeFactory.java:80)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.resolve(DependencyTreeFactory.java:80)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.lambda$resolve$1(DependencyTreeFactory.java:80)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.resolve(DependencyTreeFactory.java:80)
        at com.github.blindpirate.gogradle.core.dependency.tree.DependencyTreeFactory.getTree(DependencyTreeFactory.java:40)
        at com.github.blindpirate.gogradle.task.ResolveTask.resolveDependencies(ResolveTask.java:181)
        at com.github.blindpirate.gogradle.task.ResolveTask.resolve(ResolveTask.java:163)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)

```

**Comment by JackTiger** [comment]
go test -v code.xxxxx.com/xxxxx/platypus/net/xxxxx
```
                                                                     panic: load topo ip fail
goroutine 1 [running]:
code.xxxxxx.com/xxxxxx/platypus/net/xxxxxx.Load(0x56854d, 0x13, 0x52baa0, 0xc04206c720, 0xc04206c6f0)
main.init()
    code.xxxxx.com/xxxxx/platypus/net/xxxxxx/_test/_test main.go:46 +0x5a
exit status 2
FAIL       code.xxxxx.com/xxxxx/platypus/net/xxxxxxx   0.176s

```

**Comment by JackTiger** [comment]
```
Test for code.xxxxx.com/xxxx/platypus/xxxx/xxxx   finished, 6 succeed, 0 failed
Test for code.xxxxx.com/xxxx/platypus/xxxx/xxxx  finished, 0 succeed, 1 failed
Test for code.xxxxx.com/xxxx/platypus/xxxx/xxxx f finished, 0 succeed, 0 failed
Test for code.xxxxx.com/xxxx/platypus/xxxx/xxxx /bcd finished, 2 succeed, 0 failed
Test for code.xxxxx.com/xxxx/platypus/xxxx/xxxx /topo finished, 0 succeed, 0 failed

```

我感觉是你那边去解析关键字时，没有解析panic出现的情况，　go test -v ./... 是有log出来的。

**Comment by blindpirate** [comment]
感谢报告，原因是`init()`函数里的panic会丢失函数信息，需要额外处理。

**Comment by JackTiger** [comment]
使用gogradle构建时，`-gcflags "-N -l"` 这种参数除了我自定义方法给go build增加参数外，还有其他方式可以直接指定吗？

我看你有
```
    // 即build constraint。详见 https://golang.org/pkg/go/build/#hdr-Build_Constraints
    buildTags = ['appengine','anothertag']
```

看上去像是给指定这种tag的参数

**Comment by JackTiger** [comment]
另外，执行go test时，gogradle是不是去查找_test.go结尾的文件，然后会排除掉不是以TestXxxx开头的测试方法？这可能有点问题，我这边有些同事写的测试用例不是很规范，使用如下方式命名：Test_T_M，其中T为类型名，M为方法名，这样容易区分，但这不是Go语言的强制要求。然后再做gotest时，发现gogradle不会去跑这些测试方法，但是我手执行 go test是可以的，你可以本地验证一下

```
Package testing provides support for automated testing of Go packages. It is intended to be used in concert with the “go test” command, which automates execution of any function of the form

func TestXxx(*testing.T)
where Xxx can be any alphanumeric string (but the first letter must not be in [a-z]) and serves to identify the test routine.
```

**Comment by JackTiger** [comment]
go测试命名规则：
1、文件名必须以xx_test.go命名

2、方法必须是Test[^a-z]开头

3、方法参数必须 t *testing.T

**Comment by blindpirate** [comment]
![image](https://user-images.githubusercontent.com/12689835/27587563-6a4ffd0a-5b77-11e7-84a2-918e2275c945.png)

有什么问题么？

请附带有问题的测试用例，不要让我自己构造。

**Comment by JackTiger** [comment]
B使用vendor生成依赖，并归档到版本仓库中，同时把gogradle.lock也归档，
A依赖B构建时会存在下面的问题：

```
Execution failed for task ':resolveBuildDependencies'.
> Exception in resolution, message is:
vendor dependency code.xxxx.com/cse:GitNotationDependency{name='code.xxxx.com/CSP-GSF/GSF', commit='7a77734ef253baa056735e202b58780f7a98e64
7', urls='[git@code.xxxxx.com:CSP-GSF/GSF.git]'}/vendor/code.xxxxxx.com/cse does not exist in transitive dependencies of code.xxxxxx.com/CSP-G
SF/GSF#7a77734ef253baa056735e202b58780f7a98e647
```


经分析，是由于解析B依赖库时，B中这个库的信息即存在vendor又存在gogradle.lock文件，gogradle.lock文件中有段描述如下：

```
- name: "code.xxxxx.com/cse"
    host:
      name: "code.xxxxx.com/CSP-GSF/GSF"
      commit: "7a77734ef253baa056735e202b58780f7a98e647"
      url: "git@code.xxxxx.com:CSP-GSF/GSF.git"
      vcs: "git"
    vendorPath: "vendor/code.xxxxx.com/cse"

```

B中vendor目录结构
```
vendor/code.xxxxx.com
         |
         -------code.xxxxx.com/CSP-GSF/GSF
         |
         -------cse

```

上面lock文件可以看出，code.xxxxxx.com/cse库来源于code.xxxxx.com:CSP-GSF/GSF中的vendor，此时构建B是没有问题的，但是A对B有依赖的库解析时就会出错，此时code.xxxxx.com/cse是在B的vendor目录里，所以会提示上面的错误。

解决方案：

需要使用vendor生成依赖并归档到版本仓库中的库，不需要再将gogradl.lock提交入库，请将它删除。

**Comment by JackTiger** [comment]
我这边有个背景，A对code.xxxxx.com:CSP-GSF/GSF这个工程是没有权限的，所以需要把code.xxxxx.com:CSP-GSF/GSF打到B的Vendor里(B有权限)

**Comment by JackTiger** [comment]
使用gogradle构建：
Test for code.xxxxx.com/prp/dds/lts/local/key finished, 5 completed, 0 failed
生成的报告

```
Package code.xxxxx.com/prp/dds/lts/local/key

Classes
Class	                       Tests	  Failures	Ignored	Duration	Success rate
keyer_test.go	                   3	      0	     0	             0s	        100%
single_keyer_syn_test.go	   2	      0	     0	             0s	        100%
```
没有被测到的文件以及测试方法：

```
single_keyer_test.go

package key

func Test_SingleKeyerSetGet(t *testing.T) {
}

func Test_SingleKeyerSetGetObject(t *testing.T) {
}
```

上面的工程使用go test测试

```
go test code.xxxxx.com/prp/dds/lts/local/key
myKey &{JJ 0xc042058640 0 <nil> 0xc042042e80}
panic: interface conversion: interface {} is nil, not *basevalue.BaseV

goroutine 22 [running]:
code.xxxx.com/prp/dds/lts/local/key.(*Key).get(0xc042045240, 0xc042034000, 0xc042038d00, 0xc0420a7600, 0xc0420a75f8)
        D:/dds/dds-72b56c6bc93c28ae93da14d5b66cb57274cbbcdb-72b56c6bc93c28ae93da14d5b66cb57274cbbcdb/.gogradle/project_gopath/src/code.xxxx.c
om/prp/dds/lts/local/key/domain_factory.go:41 +0x3ab
FAIL    code.xxxx.com/prp/dds/lts/local/key   0.190s
```

**我怀疑是不是执行过程中有个测试方法failed了，导致后面的测试方法没有被执行。**

**Comment by blindpirate** [comment]
第一个问题，没看懂，请给我一个case。
```
vendor/code.xxxxx.com
         |
         -------code.xxxxx.com/CSP-GSF/GSF
         |
         -------cse
```
这是什么结构？

第二个问题，需要更多信息，不过我怀疑是某个测试中调用了os.Exit.

**Comment by JackTiger** [comment]
执行单个测试包
```
$ go test -v code.xxxx.com/prp/dds/lts/local/key
=== RUN   TestKey_UpdateSingleValueSyn
--- PASS: TestKey_UpdateSingleValueSyn (0.00s)
=== RUN   Test_SingleKeyerSetGet
myKey &{JJ 0xc042042690 0 <nil> 0xc0420b2080}
panic: interface conversion: interface {} is nil, not *basevalue.BaseV

goroutine 23 [running]:
code.xxxx.com/prp/dds/lts/local/key.(*Key).get(0xc0420ac300, 0xc042038000, 0xc04203cea0, 0xc0420a3600, 0xc0420a35f8)
        D:/dds/dds-72b56c6bc93c28ae93da14d5b66cb57274cbbcdb-72b56c6bc93c28ae93da14d5b66cb57274cbbcdb/.gogradle/project_gopath/src/code.xxxx.com/prp/dds/lts/local/key/key.go:93 +0x92
code.xxxx.com/prp/dds/lts/local/key.(*Key).GetSyn(0xc0420ac300, 0x58d780, 0x2, 0xc0420ac300, 0x0)
        D:/dds/dds-72b56c6bc93c28ae93da14d5b66cb57274cbbcdb-72b56c6bc93c28ae93da14d5b66cb57274cbbcdb/.gogradle/project_gopath/src/code.xxxx.com/prp/dds/lts/local/key/key.go:99 +0x48
code.xxxx.com/prp/dds/lts/local/key.(*asynTaskQueue).handleGetDoneCallBack(0xc0420426c8, 0xc042042690, 0x58d780, 0x2, 0x554000, 0xc0420ae1b0, 0xc0420b20a0)
        D:/dds/dds-72b56c6bc93c28ae93da14d5b66cb57274cbbcdb-72b56c6bc93c28ae93da14d5b66cb57274cbbcdb/.gogradle/project_gopath/src/code.xxxx.com/prp/dds/lts/local/key/task_queue.go:175 +0x58
code.xxxx.com/prp/dds/lts/local/key.(*domainMember).traverseTaskQueue(0xc042042690)
        D:/dds/dds-72b56c6bc93c28ae93da14d5b66cb57274cbbcdb-72b56c6bc93c28ae93da14d5b66cb57274cbbcdb/.gogradle/project_gopath/src/code.xxxx.com/prp/dds/lts/local/key/domain_asyn.go:113 +0x849
created by code.xxxx.com/prp/dds/lts/local/key.(*domainFactory).newDomain
        D:/dds/dds-72b56c6bc93c28ae93da14d5b66cb57274cbbcdb-72b56c6bc93c28ae93da14d5b66cb57274cbbcdb/.gogradle/project_gopath/src/code.xxxx.com/prp/dds/lts/local/key/domain_factory.go:41 +0x3ab
exit status 2
FAIL    code.xxxx.com/prp/dds/lts/local/key   0.171s
```

执行多个测试包：

```
$ go test -v code.xxxx.com/prp/dds/lts/local/key code.xxxx.com/prp/dds/lts/index
=== RUN   TestKey_UpdateSingleValueSyn
--- PASS: TestKey_UpdateSingleValueSyn (0.00s)
=== RUN   Test_SingleKeyerSetGet
myKey &{JJ 0xc04201a820 0 <nil> 0xc0420032c0}
panic: interface conversion: interface {} is nil, not *basevalue.BaseV

goroutine 9 [running]:
code.xxxx.com/prp/dds/lts/local/key.(*Key).get(0xc042011440, 0xc042038000, 0xc0420256c0, 0xc042091600, 0xc0420915f8)
        D:/dds/dds-72b56c6bc93c28ae93da14d5b66cb57274cbbcdb-72b56c6bc93c28ae93da14d5b66cb57274cbbcdb/.gogradle/project_gopath/src/code.xxxx.com/prp/dds/lts/local/key/key.go:93 +0x92
code.xxxx.com/prp/dds/lts/local/key.(*Key).GetSyn(0xc042011440, 0x58d780, 0x2, 0xc042011440, 0x0)
        D:/dds/dds-72b56c6bc93c28ae93da14d5b66cb57274cbbcdb-72b56c6bc93c28ae93da14d5b66cb57274cbbcdb/.gogradle/project_gopath/src/code.xxxx.com/prp/dds/lts/local/key/key.go:99 +0x48
code.xxxx.com/prp/dds/lts/local/key.(*asynTaskQueue).handleGetDoneCallBack(0xc04201a858, 0xc04201a820, 0x58d780, 0x2, 0x554000, 0xc042009240, 0xc0420032e0)
        D:/dds/dds-72b56c6bc93c28ae93da14d5b66cb57274cbbcdb-72b56c6bc93c28ae93da14d5b66cb57274cbbcdb/.gogradle/project_gopath/src/code.xxxx.com/prp/dds/lts/local/key/task_queue.go:175 +0x58
code.xxxx.com/prp/dds/lts/local/key.(*domainMember).traverseTaskQueue(0xc04201a820)
        D:/dds/dds-72b56c6bc93c28ae93da14d5b66cb57274cbbcdb-72b56c6bc93c28ae93da14d5b66cb57274cbbcdb/.gogradle/project_gopath/src/code.xxxx.com/prp/dds/lts/local/key/domain_asyn.go:113 +0x849
created by code.xxxx.com/prp/dds/lts/local/key.(*domainFactory).newDomain
        D:/dds/dds-72b56c6bc93c28ae93da14d5b66cb57274cbbcdb-72b56c6bc93c28ae93da14d5b66cb57274cbbcdb/.gogradle/project_gopath/src/code.xxxx.com/prp/dds/lts/local/key/domain_factory.go:41 +0x3ab
FAIL    code.xxxx.com/prp/dds/lts/local/key   0.162s
=== RUN   TestSingleKey
--- PASS: TestSingleKey (0.00s)
=== RUN   TestMultipleKey
--- PASS: TestMultipleKey (0.00s)
=== RUN   TestRemoveTwice
--- PASS: TestRemoveTwice (0.00s)
PASS
ok      code.xxxx.com/prp/dds/lts/index       0.172s
```

**Comment by JackTiger** [comment]
Go Test Case:(测试case构建出来了，是因为go test时丢到goroutine里去执行了)

```
package demo

import (
	"fmt"
	"testing"
	"time"
)

type demoStr struct {
	data interface{}
}

type SingleKeyer interface {
	Get(userData interface{}) (interface{}, error)
}

func (d *demoStr) Get(userData interface{}) (interface{}, error) {
	return d.data.(*testStr).Get()
}

type testStr struct {
}

func (d *testStr) Get() (interface{}, error) {
	return "testStr", nil
}

func Test_SingleKeyerSetGet(t *testing.T) {
	go func() {
		demoStruct := new(demoStr)
		fmt.Println("demoStruct", demoStruct)
		demoStruct.Get("myKey")
	}()

	time.Sleep(1 * time.Second)
	t.Log("Test Test_SingleKeyerSetGet End")
}
```

**Comment by blindpirate** [comment]
好的，十分感谢。

**Comment by JackTiger** [comment]
这个是我之前遇到的问题：

B使用vendor生成依赖，并归档到版本仓库中，同时把gogradle.lock也归档，
A依赖B构建时会存在下面的问题：

```
Execution failed for task ':resolveBuildDependencies'.
> Exception in resolution, message is:
vendor dependency code.xxxx.com/cse:GitNotationDependency{name='code.xxxx.com/CSP-GSF/GSF', commit='7a77734ef253baa056735e202b58780f7a98e64
7', urls='[git@code.xxxxx.com:CSP-GSF/GSF.git]'}/vendor/code.xxxxxx.com/cse does not exist in transitive dependencies of code.xxxxxx.com/CSP-G
SF/GSF#7a77734ef253baa056735e202b58780f7a98e647
```


经分析，是由于解析B依赖库时，B中这个库的信息即存在vendor又存在gogradle.lock文件，gogradle.lock文件中有段描述如下：

```
- name: "code.xxxxx.com/cse"
    host:
      name: "code.xxxxx.com/CSP-GSF/GSF"
      commit: "7a77734ef253baa056735e202b58780f7a98e647"
      url: "git@code.xxxxx.com:CSP-GSF/GSF.git"
      vcs: "git"
    vendorPath: "vendor/code.xxxxx.com/cse"

```

B中vendor目录结构
```
vendor/code.xxxxx.com
         |
         -------/CSP-GSF/GSF
         |
         -------cse

```

上面lock文件可以看出，code.xxxxxx.com/cse库来源于code.xxxxx.com:CSP-GSF/GSF中的vendor，此时构建B是没有问题的，但是A对B有依赖的库解析时就会出错，此时code.xxxxx.com/cse是在B的vendor目录里，所以会提示上面的错误。

解决方案：

需要使用vendor生成依赖并归档到版本仓库中的库，不需要再将gogradl.lock提交入库，请将它删除。


场景你可以参看我的case（构建出来有点晚，网络太差了，环境准备花了好多时间）
https://github.com/JackTiger/demoA
https://github.com/JackTiger/demoB
https://github.com/JackTiger/demoC

类比我这边的A， B,    code.xxxxx.com/CSP-GSF/GSF， 最开始的日志可以看出是按照lock文件里面去查找的，没有按照vendor，所以不清楚是什么原因导致的。

**Comment by JackTiger** [comment]
@blindpirate
